//! MCP JSON-RPC boundary, in both of Java's authentication modes.
//!
//! Alongside the Rust AI-engine catalog (`stirling_describe_operation`,
//! `stirling_ai`), this owns reusable file artifacts (`stirling_upload`,
//! `stirling_download`), Java's per-category PDF tools (`stirling_pages`,
//! `stirling_convert`, `stirling_misc`, `stirling_security`), and direct
//! dispatch of a real Stirling processing operation (`stirling_operation`, a
//! Rust-only extension Java does not have), reusing the existing owner-scoped
//! [`crate::job_manager::JobManager`] for storage and the same in-process
//! router dispatch [`crate::pipeline`] uses to run a pipeline step.
//!
//! Authentication follows Java's `McpSecurityConfig` mode split exactly:
//! `mcp.auth.mode=apikey` accepts a Stirling per-user API key
//! (`McpApiKeyAuthFilter` semantics — every valid key is statically granted
//! BOTH `mcp.tools.read` and `mcp.tools.write`), while **any other mode value
//! runs the `OAuth2` resource-server chain**: bearer JWTs validated through
//! [`crate::mcp_oauth`] (issuer + JWKS + RFC 8707 audience), token subjects
//! bound to provisioned Stirling accounts (`McpUserBindingFilter` → 403
//! `insufficient_account`), RFC 9728 protected-resource metadata served under
//! `/.well-known/oauth-protected-resource`, and a 401 challenge carrying the
//! metadata pointer. In OAuth mode the token's `scope` claim is the caller's
//! real per-call grant, enforced tool-by-tool through [`McpCallContext`]
//! exactly like Java's `McpCallContext.hasScope`.

use std::{
    collections::{BTreeMap, BTreeSet},
    io::Read as _,
    path::PathBuf,
    sync::{Arc, LazyLock, Mutex},
    time::{Duration, Instant},
};

use axum::{
    Router,
    body::to_bytes,
    extract::{Request, State},
    http::{HeaderMap, HeaderValue, StatusCode, Uri, header},
    response::{IntoResponse, Response},
    routing::{get, post},
};
use base64::{Engine as _, engine::general_purpose::STANDARD};
use reqwest::blocking::Client;
use serde_json::{Map, Value, json};
use tempfile::TempDir;
use tokio::task;
use tower::ServiceExt as _;
use tracing::warn;
use zeroize::Zeroizing;

use crate::{
    job_manager::{JobManager, JobOwner},
    mcp_oauth::{self, McpOAuthVerifier, PROTECTED_RESOURCE_METADATA_PATH},
    pdf_ai_comments::AiCommentEngineSettings,
    pipeline::{PipelineFile, PipelineOperation, SupportingFiles},
    runtime_config::{McpConfig, RuntimeConfig},
    runtime_metrics::application_version,
    security::{AuthContext, SecurityError, SecurityStore},
};

const MCP_PATH: &str = "/mcp";
const CAPABILITIES_PATH: &str = "/api/v1/agents/capabilities";
const PREFERRED_PROTOCOL_VERSION: &str = "2025-06-18";
const SUPPORTED_PROTOCOL_VERSIONS: &[&str] = &["2025-06-18", "2025-03-26", "2024-11-05"];
const READ_SCOPE: &str = "mcp.tools.read";
const WRITE_SCOPE: &str = "mcp.tools.write";
const MAX_MANIFEST_BYTES: u64 = 1024 * 1024;
const MAX_ENGINE_RESULT_BYTES: u64 = 4 * 1024 * 1024;
const MAX_CAPABILITIES: usize = 256;
const MAX_CAPABILITY_ID_BYTES: usize = 128;
const MAX_DESCRIPTION_BYTES: usize = 4096;
const MAX_SCOPE_BYTES: usize = 128;
const MAX_ROUTE_BYTES: usize = 512;
const MAX_SCHEMA_BYTES: usize = 128 * 1024;

/// The generated per-operation parameter schemas, single-sourced from the AI
/// engine's catalog file so `task engine:tool-models` stays the only
/// regeneration path. `include_str!` resolves relative to this source file.
const OPERATION_CATALOG_JSON: &str =
    include_str!("../../stirling-ai-engine/src/operation_catalog.json");

/// The MCP supplement to the AI catalog: the flat operations the AI catalog's
/// generator deliberately excludes for AI-engine reasons (cert-sign,
/// get-info-on-pdf, overlay-pdfs, ...) but that Java's `McpToolCatalog` -
/// which has no exclusion list - still indexes into its category enums.
/// Generated by the same `task engine:tool-models` run as the AI catalog.
const OPERATION_SUPPLEMENT_JSON: &str = include_str!("mcp_operation_supplement.json");

/// Java's `OperationCategory`: maps an `/api/v1/` namespace to a category
/// tool. The AI category is handled separately by `stirling_ai`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum PdfCategory {
    Convert,
    Pages,
    Misc,
    Security,
}

impl PdfCategory {
    const ALL: [Self; 4] = [Self::Convert, Self::Pages, Self::Misc, Self::Security];

    fn url_prefix(self) -> &'static str {
        match self {
            Self::Convert => "/api/v1/convert/",
            Self::Pages => "/api/v1/general/",
            Self::Misc => "/api/v1/misc/",
            Self::Security => "/api/v1/security/",
        }
    }

    fn tool_name(self) -> &'static str {
        match self {
            Self::Convert => "stirling_convert",
            Self::Pages => "stirling_pages",
            Self::Misc => "stirling_misc",
            Self::Security => "stirling_security",
        }
    }

    /// Tool descriptions, verbatim from Java's category tool classes.
    fn tool_description(self) -> &'static str {
        match self {
            Self::Convert => {
                "Convert files between PDF and other formats (PDF<->Word, PDF<->image, HTML->PDF, etc.). Inspect the `operation` enum, then call stirling_describe_operation with the chosen op to get its parameters JSON Schema before calling this tool."
            }
            Self::Pages => {
                "Manipulate PDF pages: merge, split, rotate, rearrange, crop, delete, overlay, add blank pages. Call stirling_describe_operation with the chosen op to get its parameters schema before invoking this tool."
            }
            Self::Misc => {
                "Miscellaneous PDF operations: compress, OCR, stamp / watermark, edit metadata, flatten, repair, and similar utilities. Call stirling_describe_operation with the chosen op to get its parameters schema before invoking this tool."
            }
            Self::Security => {
                "Security-related PDF operations: password add/remove, redact, sanitize, certify / sign with cert, validate signature, add watermark. Call stirling_describe_operation with the chosen op to get its parameters schema before invoking this tool."
            }
        }
    }
}

/// One MCP-exposable PDF operation derived from the generated catalog, the
/// Rust analogue of Java's `OperationMeta` for `JAVA_ENDPOINT` targets.
#[derive(Debug)]
struct PdfOperation {
    id: String,
    category: PdfCategory,
    endpoint_path: String,
    summary: String,
    parameters_schema: Value,
}

/// PDF operations keyed by id, derived once from the compiled-in catalog plus
/// its MCP supplement (together covering every flat path Java's
/// `McpToolCatalog.discover` indexes) with Java's `extractOpId` semantics: the
/// op id is the flat URL tail only, so nested or parametrised tails are
/// skipped. Every Java convert endpoint is nested (`/convert/pdf/word`), so -
/// exactly as in Java - the `stirling_convert` enum is genuinely empty.
/// Java's `putIfAbsent` (first-handler-wins) duplicate rule maps to
/// first-wins in merged path order; catalog ids are currently unique so it
/// never triggers.
static PDF_OPERATIONS: LazyLock<BTreeMap<String, PdfOperation>> = LazyLock::new(|| {
    let Ok(mut catalog) = serde_json::from_str::<BTreeMap<String, Value>>(OPERATION_CATALOG_JSON)
    else {
        return BTreeMap::new();
    };
    let supplement = serde_json::from_str::<BTreeMap<String, Value>>(OPERATION_SUPPLEMENT_JSON)
        .unwrap_or_default();
    for (path, schema) in supplement {
        catalog.entry(path).or_insert(schema);
    }
    let mut operations = BTreeMap::new();
    for (path, schema) in catalog {
        let Some((category, id)) = PdfCategory::ALL.iter().find_map(|category| {
            let tail = path.strip_prefix(category.url_prefix())?;
            (!tail.trim().is_empty() && !tail.contains('/') && !tail.contains('{'))
                .then(|| (*category, tail.to_owned()))
        }) else {
            continue;
        };
        // Java prefers the `@Operation` summary; the generated catalog does
        // not carry it, so use the request-model description when present and
        // fall back to Java's prettified id otherwise.
        let summary = schema
            .get("description")
            .and_then(Value::as_str)
            .map_or_else(|| id.replace('-', " "), str::to_owned);
        operations.entry(id.clone()).or_insert(PdfOperation {
            id,
            category,
            endpoint_path: path,
            summary,
            parameters_schema: schema,
        });
    }
    operations
});

#[derive(Clone)]
struct McpState {
    config: McpConfig,
    store: Arc<SecurityStore>,
    catalog: Arc<AiCapabilityCatalog>,
    job_manager: Arc<JobManager>,
    dispatch_router: Router,
    runtime_config: Arc<RuntimeConfig>,
    /// `Some` when the `OAuth2` resource-server chain is active (any
    /// `mcp.auth.mode` other than exactly `apikey`, mirroring Java's
    /// `isApiKeyMode`); `None` in API-key mode.
    oauth: Option<Arc<McpOAuthVerifier>>,
}

/// Per-call identity and granted scopes — Java's `McpCallContext`. In API-key
/// mode every valid key is statically granted both tool scopes
/// (`McpApiKeyAuthFilter` parity); in OAuth mode the grant is the validated
/// token's real `scope` claim, so per-tool checks genuinely gate callers.
#[derive(Clone, Debug)]
struct McpCallContext {
    auth: AuthContext,
    scopes_enabled: bool,
    granted_scopes: BTreeSet<String>,
}

impl McpCallContext {
    /// The static both-scopes grant Java's API-key filter attaches to every
    /// valid key.
    fn for_api_key(auth: AuthContext, scopes_enabled: bool) -> Self {
        Self {
            auth,
            scopes_enabled,
            granted_scopes: BTreeSet::from([READ_SCOPE.to_owned(), WRITE_SCOPE.to_owned()]),
        }
    }

    /// Java `McpCallContext.hasScope`: everything passes while scope
    /// enforcement is off or the requirement is blank; otherwise the scope
    /// must have been granted.
    fn has_scope(&self, required: &str) -> bool {
        !self.scopes_enabled || required.trim().is_empty() || self.granted_scopes.contains(required)
    }
}

#[derive(Clone)]
struct EngineConnection {
    enabled: bool,
    base_url: String,
    timeout: Duration,
    shared_secret: Option<String>,
}

impl EngineConnection {
    fn from_settings(settings: &AiCommentEngineSettings) -> Self {
        Self {
            enabled: settings.enabled(),
            base_url: settings.base_url().to_owned(),
            timeout: settings.timeout(),
            shared_secret: settings.shared_secret().map(ToOwned::to_owned),
        }
    }
}

#[derive(Clone, Debug)]
struct AiCapability {
    id: String,
    description: String,
    input_schema: Value,
    required_scope: String,
    route: Option<String>,
}

struct AiCapabilityCatalog {
    connection: EngineConnection,
    refresh_interval: Duration,
    cache: Mutex<CapabilityCache>,
}

#[derive(Default)]
struct CapabilityCache {
    operations: BTreeMap<String, AiCapability>,
    last_attempt: Option<Instant>,
    refreshing: bool,
}

impl AiCapabilityCatalog {
    fn new(connection: EngineConnection, refresh_minutes: u64) -> Self {
        Self {
            connection,
            refresh_interval: Duration::from_secs(refresh_minutes.max(1).saturating_mul(60)),
            cache: Mutex::new(CapabilityCache::default()),
        }
    }

    async fn snapshot(&self) -> BTreeMap<String, AiCapability> {
        if !self.connection.enabled {
            if let Ok(mut cache) = self.cache.lock() {
                cache.operations.clear();
                cache.last_attempt = Some(Instant::now());
                cache.refreshing = false;
            }
            return BTreeMap::new();
        }

        let should_refresh = match self.cache.lock() {
            Ok(mut cache) => {
                let due = cache.last_attempt.is_none_or(|last| {
                    Instant::now().saturating_duration_since(last) >= self.refresh_interval
                });
                if due && !cache.refreshing {
                    cache.refreshing = true;
                    cache.last_attempt = Some(Instant::now());
                    true
                } else {
                    false
                }
            }
            Err(_) => return BTreeMap::new(),
        };

        if should_refresh {
            let connection = self.connection.clone();
            let refreshed = task::spawn_blocking(move || fetch_manifest(&connection)).await;
            if let Ok(mut cache) = self.cache.lock() {
                cache.refreshing = false;
                match refreshed {
                    Ok(Ok(operations)) => cache.operations = operations,
                    Ok(Err(error)) => {
                        warn!(%error, "MCP AI capability refresh failed; retaining last known manifest");
                    }
                    Err(error) => warn!(%error, "MCP AI capability refresh worker failed"),
                }
            }
        }

        self.cache
            .lock()
            .map(|cache| cache.operations.clone())
            .unwrap_or_default()
    }
}

#[derive(Debug, thiserror::Error)]
enum EngineError {
    #[error("AI engine URL is invalid")]
    InvalidUrl,
    #[error("AI engine client could not be created")]
    Client,
    #[error("AI engine request failed")]
    Request,
    #[error("AI engine returned HTTP {0}")]
    Status(u16),
    #[error("AI engine response exceeded its configured safety limit")]
    ResponseTooLarge,
    #[error("AI engine response could not be read")]
    ResponseRead,
    #[error("AI capability manifest is invalid")]
    InvalidManifest,
}

/// Builds the MCP router in the configured authentication mode. Mirroring
/// Java's `McpSecurityConfig.mcpSecurityFilterChain`, `apikey` (exact,
/// case-insensitive) mounts the API-key chain, and **every other mode value —
/// including blank or a near-miss like `api-key` — mounts the `OAuth2`
/// resource-server chain**, which also claims the RFC 9728 protected-resource
/// metadata paths.
pub(crate) fn routes(
    config: McpConfig,
    store: Arc<SecurityStore>,
    engine_settings: &AiCommentEngineSettings,
    job_manager: Arc<JobManager>,
    dispatch_router: Router,
    runtime_config: Arc<RuntimeConfig>,
) -> Router {
    if !config.enabled {
        return Router::new();
    }
    let api_key_mode = config.auth.mode.trim().eq_ignore_ascii_case("apikey");
    let oauth = if api_key_mode {
        None
    } else {
        log_oauth_config_findings(&config);
        Some(Arc::new(McpOAuthVerifier::from_config(&config)))
    };
    let catalog = Arc::new(AiCapabilityCatalog::new(
        EngineConnection::from_settings(engine_settings),
        config.engine_capability_refresh_minutes,
    ));
    let oauth_mode = oauth.is_some();
    let state = Arc::new(McpState {
        config,
        store,
        catalog,
        job_manager,
        dispatch_router,
        runtime_config,
        oauth,
    });
    let mut router = Router::new().route(MCP_PATH, post(handle));
    if oauth_mode {
        // RFC 9728 section 3.1: the path-inserted form for a resource with a
        // path component ({metadata}/mcp) plus the bare document — Java claims
        // both (and all subpaths) in its OAuth chain's security matcher.
        router = router
            .route(
                PROTECTED_RESOURCE_METADATA_PATH,
                get(protected_resource_metadata_handler),
            )
            .route(
                "/.well-known/oauth-protected-resource/{*resource}",
                get(protected_resource_metadata_handler),
            );
    }
    router.with_state(state)
}

/// Startup findings for the OAuth chain, a condensed port of Java's
/// `McpConfigValidator` WARN cases so a fail-closed misconfiguration shows up
/// in the logs instead of as a later rejected-token 401.
fn log_oauth_config_findings(config: &McpConfig) {
    let auth = &config.auth;
    let mode = auth.mode.trim();
    if !mode.is_empty() && !mode.eq_ignore_ascii_case("oauth") {
        warn!(
            mode = auth.mode,
            "mcp.auth.mode is not recognized (expected 'oauth' or 'apikey'); it falls back to the \
             OAuth chain, which rejects every token unless issuer-uri and resource-id are set. A \
             near-miss like 'api-key' is NOT treated as API-key mode."
        );
    }
    if auth.issuer_uri.trim().is_empty() {
        warn!(
            "mcp.auth.issuer-uri is not set: the JWT validator fails closed and rejects every \
             token."
        );
    }
    if auth.resource_id.trim().is_empty()
        && !auth
            .accepted_audiences
            .iter()
            .any(|audience| !audience.trim().is_empty())
    {
        warn!(
            "neither mcp.auth.resource-id nor mcp.auth.accepted-audiences is set: the audience \
             validator fails closed and rejects every token (RFC 8707)."
        );
    }
    if !auth.require_existing_account {
        warn!(
            "mcp.auth.require-existing-account=false is not honored by the Rust MCP boundary: a \
             validated token subject must still resolve to a provisioned, enabled Stirling \
             account (fail-closed divergence documented in rust/contracts/mcp.md)."
        );
    }
}

/// Serves the RFC 9728 protected-resource metadata document (GET, no
/// authentication), Java's Spring `OAuth2ProtectedResourceMetadataFilter` +
/// `buildResourceMetadata` customizer.
async fn protected_resource_metadata_handler(
    State(state): State<Arc<McpState>>,
    uri: Uri,
    headers: HeaderMap,
) -> Response {
    json_response(
        StatusCode::OK,
        mcp_oauth::protected_resource_metadata(&state.config, &headers, uri.path()),
    )
}

async fn handle(State(state): State<Arc<McpState>>, request: Request) -> Response {
    let (parts, body) = request.into_parts();
    if !is_json_content_type(&parts.headers) {
        return StatusCode::UNSUPPORTED_MEDIA_TYPE.into_response();
    }
    if declared_body_too_large(&parts.headers, state.config.max_request_bytes) {
        return payload_too_large(state.config.max_request_bytes);
    }
    let Ok(body) = to_bytes(body, state.config.max_request_bytes).await else {
        return payload_too_large(state.config.max_request_bytes);
    };
    let context = match authenticate(&state, &parts.headers).await {
        Ok(context) => context,
        Err(response) => return response,
    };
    let Ok(body) = serde_json::from_slice::<Value>(&body) else {
        return json_response(
            StatusCode::BAD_REQUEST,
            rpc_failure(Value::Null, -32700, "Request body is not valid JSON"),
        );
    };
    let Some(request) = decode_request(&body) else {
        return json_response(
            StatusCode::BAD_REQUEST,
            rpc_failure(
                Value::Null,
                -32600,
                "Body is not a valid JSON-RPC 2.0 request",
            ),
        );
    };
    if request.notification {
        return StatusCode::NO_CONTENT.into_response();
    }
    let result = dispatch(&state, &context, &request).await;
    json_response(StatusCode::OK, result)
}

struct RpcRequest {
    id: Value,
    method: String,
    params: Option<Value>,
    notification: bool,
}

fn decode_request(body: &Value) -> Option<RpcRequest> {
    let object = body.as_object()?;
    if object.get("jsonrpc")?.as_str()? != "2.0" {
        return None;
    }
    let method = object.get("method")?.as_str()?.to_owned();
    let id = object.get("id").cloned().unwrap_or(Value::Null);
    Some(RpcRequest {
        notification: id.is_null(),
        id,
        method,
        params: object.get("params").cloned(),
    })
}

async fn dispatch(state: &McpState, context: &McpCallContext, request: &RpcRequest) -> Value {
    match request.method.as_str() {
        "initialize" => rpc_success(
            request.id.clone(),
            initialize_result(request.params.as_ref()),
        ),
        "tools/list" => {
            let operations = visible_operations(state).await;
            rpc_success(request.id.clone(), tools_list_result(state, &operations))
        }
        "tools/call" => handle_tools_call(state, context, request).await,
        "ping" | "notifications/initialized" => {
            rpc_success(request.id.clone(), Value::Object(Map::new()))
        }
        method => rpc_failure(
            request.id.clone(),
            -32601,
            &format!("Method not found: {method}"),
        ),
    }
}

fn initialize_result(params: Option<&Value>) -> Value {
    let requested = params
        .and_then(|params| params.get("protocolVersion"))
        .and_then(Value::as_str);
    let negotiated = requested
        .filter(|requested| SUPPORTED_PROTOCOL_VERSIONS.contains(requested))
        .unwrap_or(PREFERRED_PROTOCOL_VERSION);
    json!({
        "protocolVersion": negotiated,
        "capabilities": {"tools": {}},
        "serverInfo": {
            "name": "stirling-pdf-mcp",
            "version": application_version(),
        }
    })
}

async fn handle_tools_call(
    state: &McpState,
    context: &McpCallContext,
    request: &RpcRequest,
) -> Value {
    let Some(params) = request.params.as_ref().and_then(Value::as_object) else {
        return rpc_failure(request.id.clone(), -32602, "Missing params for tools/call");
    };
    let Some(name) = params.get("name").and_then(Value::as_str) else {
        return rpc_failure(request.id.clone(), -32602, "Missing tool name");
    };
    let arguments = params
        .get("arguments")
        .cloned()
        .unwrap_or_else(|| Value::Object(Map::new()));
    let operations = visible_operations(state).await;
    let result = match name {
        "stirling_describe_operation" => describe_operation(state, &arguments, &operations),
        "stirling_ai" => call_ai(state, context, &arguments, &operations).await,
        "stirling_upload" => upload_file(state, context, &arguments).await,
        "stirling_download" => download_file(state, context, &arguments).await,
        "stirling_pages" => call_category(state, context, PdfCategory::Pages, &arguments).await,
        "stirling_convert" => call_category(state, context, PdfCategory::Convert, &arguments).await,
        "stirling_misc" => call_category(state, context, PdfCategory::Misc, &arguments).await,
        "stirling_security" => {
            call_category(state, context, PdfCategory::Security, &arguments).await
        }
        "stirling_operation" => run_operation(state, context, &arguments).await,
        _ => {
            return rpc_failure(request.id.clone(), -32602, &format!("Unknown tool: {name}"));
        }
    };
    rpc_success(request.id.clone(), result)
}

/// The category's operations as currently visible: allow/block-list filtered
/// (by op id, matching Java) and endpoint-enabled filtered the way Java uses
/// `EndpointConfiguration.isEndpointEnabledForUri`; sorted by id.
fn enabled_pdf_operations(state: &McpState, category: PdfCategory) -> Vec<&'static PdfOperation> {
    PDF_OPERATIONS
        .values()
        .filter(|operation| operation.category == category)
        .filter(|operation| operation_allowed(&state.config, &operation.id))
        .filter(|operation| {
            state
                .runtime_config
                .is_endpoint_enabled_for_uri(&operation.endpoint_path)
        })
        .collect()
}

/// Java `McpToolCatalog.findByOperationId` for the PDF slice: a blocked or
/// endpoint-disabled PDF operation is `Hidden`, never absent - it must not
/// fall through to a same-id AI capability.
enum PdfLookup {
    Enabled(&'static PdfOperation),
    Hidden,
    Unknown,
}

fn find_pdf_operation(state: &McpState, id: &str) -> PdfLookup {
    let Some(operation) = PDF_OPERATIONS.get(id) else {
        return PdfLookup::Unknown;
    };
    if operation_allowed(&state.config, id)
        && state
            .runtime_config
            .is_endpoint_enabled_for_uri(&operation.endpoint_path)
    {
        PdfLookup::Enabled(operation)
    } else {
        PdfLookup::Hidden
    }
}

/// Runs one category tool call with Java `AbstractCategoryTool.call` semantics:
/// a missing, unknown, wrong-category, blocked, or endpoint-disabled operation
/// returns the category's operation-list error, and — in Java's exact order,
/// after the operation resolves — the caller must hold the operation's
/// required scope (`mcp.tools.write` for every PDF operation). API keys carry
/// both scopes statically; OAuth callers are gated by their token's real
/// `scope` claim.
async fn call_category(
    state: &McpState,
    context: &McpCallContext,
    category: PdfCategory,
    arguments: &Value,
) -> Value {
    let Some(operation_id) = operation_argument(arguments) else {
        return operation_list_error(state, category, None);
    };
    let operation = match find_pdf_operation(state, operation_id) {
        PdfLookup::Enabled(operation) if operation.category == category => operation,
        _ => return operation_list_error(state, category, Some(operation_id)),
    };
    if !context.has_scope(WRITE_SCOPE) {
        return tool_error(&format!(
            "Insufficient scope: this operation requires '{WRITE_SCOPE}'."
        ));
    }
    dispatch_operation(
        state,
        context,
        arguments,
        &operation.endpoint_path,
        &operation.id,
    )
    .await
}

/// Java `AbstractCategoryTool.operationListError`: the error for a missing or
/// unknown operation, listing this category's available ids and summaries.
fn operation_list_error(state: &McpState, category: PdfCategory, bad_op_id: Option<&str>) -> Value {
    let mut message = match bad_op_id {
        None => format!(
            "Missing required argument 'operation' for {}",
            category.tool_name()
        ),
        Some(bad_op_id) => format!(
            "Unknown or disabled operation '{bad_op_id}' for {}",
            category.tool_name()
        ),
    };
    let operations = enabled_pdf_operations(state, category);
    if operations.is_empty() {
        message.push_str(". No operations are currently available in this category.");
    } else {
        message.push_str(". Available operations:");
        for operation in &operations {
            message.push_str("\n- ");
            message.push_str(&operation.id);
            message.push_str(" - ");
            message.push_str(&operation.summary);
        }
        message.push_str("\nRe-call this tool with a valid 'operation'.");
    }
    tool_error(&message)
}

async fn visible_operations(state: &McpState) -> BTreeMap<String, AiCapability> {
    state
        .catalog
        .snapshot()
        .await
        .into_iter()
        .filter(|(id, _)| operation_allowed(&state.config, id))
        .collect()
}

fn operation_allowed(config: &McpConfig, id: &str) -> bool {
    if config
        .blocked_operations
        .iter()
        .any(|blocked| blocked == id)
    {
        return false;
    }
    config.allowed_operations.is_empty()
        || config
            .allowed_operations
            .iter()
            .any(|allowed| allowed == id)
}

fn tools_list_result(state: &McpState, operations: &BTreeMap<String, AiCapability>) -> Value {
    let mut tools = vec![
        json!({
            "name": "stirling_describe_operation",
            "description": "Return the full JSON Schema for one Stirling operation's parameters. Call this before invoking a category tool to learn the exact shape of `parameters`. Argument: { operation: <op-id> } where <op-id> appears in the enum of any category tool (stirling_convert, _pages, _misc, _security, _ai).",
            "inputSchema": describe_schema(),
        }),
        json!({
            "name": "stirling_ai",
            "description": "Invoke a Stirling AI agent capability. Call stirling_describe_operation with the chosen capability id before invoking this tool.",
            "inputSchema": ai_tool_schema(operations),
        }),
        json!({
            "name": "stirling_upload",
            "description": "Store a file server-side and get back a fileId to reuse across operations. Recommended only for large files or multi-step workflows; for a single operation on a typical file, pass the file inline via the operation's `file` argument instead. Argument: { file: <base64>, fileName?: <name> }.",
            "inputSchema": upload_tool_schema(),
        }),
        json!({
            "name": "stirling_download",
            "description": "Fetch a stored file's content by fileId (e.g. an operation result), returned inline as base64. Recommended only when a result was too large to be returned inline. Argument: { fileId: <id> }.",
            "inputSchema": download_tool_schema(),
        }),
    ];
    for category in PdfCategory::ALL {
        tools.push(json!({
            "name": category.tool_name(),
            "description": category.tool_description(),
            "inputSchema": category_tool_schema(state, category),
        }));
    }
    // Rust-only extension: Java has no path-addressed dispatch tool.
    tools.push(json!({
        "name": "stirling_operation",
        "description": "Run a real Stirling PDF processing operation (e.g. split, merge, compress, convert) by its API path, not an AI capability. Pass the input file inline as base64 via `file`, or a `fileId` from stirling_upload or a prior operation's result.",
        "inputSchema": operation_tool_schema(),
    }));
    json!({ "tools": tools })
}

/// Java `AbstractCategoryTool.inputSchema`, shape-for-shape: `operation`
/// (enum with an id-and-summary description), free-form `parameters`, and the
/// `file`/`fileName`/`fileId` input trio; only `operation` is required.
fn category_tool_schema(state: &McpState, category: PdfCategory) -> Value {
    let operations = enabled_pdf_operations(state, category);
    let ids = operations
        .iter()
        .map(|operation| Value::String(operation.id.clone()))
        .collect::<Vec<_>>();
    let mut description = String::from(
        "Operation id from this category. Call stirling_describe_operation first to learn the exact parameters schema. Available operations:",
    );
    for operation in &operations {
        description.push_str("\n- ");
        description.push_str(&operation.id);
        description.push_str(" - ");
        description.push_str(&operation.summary);
    }
    json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "operation": {"type": "string", "enum": ids, "description": description},
            "parameters": {
                "type": "object",
                "description": "Per-operation parameters. Schema available via stirling_describe_operation.",
                "additionalProperties": true,
            },
            "file": {
                "type": "string",
                "description": "Base64-encoded file content to process. The recommended way to provide a file for most uses. Bounded by the MCP request size limit; for very large files use 'fileId' instead.",
            },
            "fileName": {
                "type": "string",
                "description": "Optional original filename (with extension) for the input; helps operations that key off file type.",
            },
            "fileId": {
                "type": "string",
                "description": "Reference to a file already stored via stirling_upload. Recommended only for large files or multi-step workflows; most users should pass the file inline via 'file' instead.",
            },
        },
        "required": ["operation"],
    })
}

fn upload_tool_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "file": {"type": "string", "description": "Base64-encoded file content."},
            "fileName": {"type": "string", "description": "Optional original filename (with extension)."},
        },
        "required": ["file"],
    })
}

fn download_tool_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "fileId": {"type": "string", "description": "Id of a stored file (e.g. an operation result's fileId)."},
        },
        "required": ["fileId"],
    })
}

fn operation_tool_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "operation": {
                "type": "string",
                "description": "The Stirling API path to call, e.g. /api/v1/general/split-pages.",
            },
            "file": {"type": "string", "description": "Base64-encoded input file content."},
            "fileId": {
                "type": "string",
                "description": "Id of a previously stored file (from stirling_upload or a prior operation's result), used instead of 'file'.",
            },
            "fileName": {"type": "string", "description": "Optional filename for the input file."},
            "parameters": {
                "type": "object",
                "description": "Operation-specific form parameters, matching the operation's own API request fields.",
            },
        },
        "required": ["operation"],
    })
}

fn describe_schema() -> Value {
    json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "operation": {
                "type": "string",
                "description": "Operation id (e.g. compress-pdf, pdf-to-word, q-and-a). See category tool enums."
            }
        },
        "required": ["operation"]
    })
}

fn ai_tool_schema(operations: &BTreeMap<String, AiCapability>) -> Value {
    let ids = operations
        .keys()
        .cloned()
        .map(Value::String)
        .collect::<Vec<_>>();
    let mut description =
        String::from("Capability id from the engine manifest. Available capabilities:");
    for operation in operations.values() {
        description.push_str("\n- ");
        description.push_str(&operation.id);
        description.push_str(" - ");
        description.push_str(&operation.description);
    }
    json!({
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "operation": {"type": "string", "enum": ids, "description": description},
            "parameters": {"type": "object", "description": "Per-capability parameters.", "additionalProperties": true},
            "fileId": {
                "type": "string",
                "description": "Reference to a previously-uploaded PDF in Stirling's job store. Required for capabilities that consume a document."
            }
        },
        "required": ["operation"]
    })
}

/// Describes one operation, PDF operations first (matching Java's catalog
/// lookup order): a blocked or endpoint-disabled PDF operation reports
/// "unknown or disabled" and never falls through to a same-id AI capability.
fn describe_operation(
    state: &McpState,
    arguments: &Value,
    operations: &BTreeMap<String, AiCapability>,
) -> Value {
    let Some(operation_id) = operation_argument(arguments) else {
        return tool_error("Missing required argument: operation");
    };
    match find_pdf_operation(state, operation_id) {
        PdfLookup::Enabled(operation) => {
            return tool_text(
                &json!({
                    "operation": operation.id,
                    "category": operation.category.tool_name(),
                    "summary": operation.summary,
                    "endpoint": operation.endpoint_path,
                    "requiredScope": WRITE_SCOPE,
                    "parametersSchema": operation.parameters_schema,
                })
                .to_string(),
            );
        }
        PdfLookup::Hidden => {
            return tool_error(&format!("Unknown or disabled operation: {operation_id}"));
        }
        PdfLookup::Unknown => {}
    }
    let Some(operation) = operations.get(operation_id) else {
        return tool_error(&format!("Unknown or disabled operation: {operation_id}"));
    };
    tool_text(
        &json!({
            "operation": operation.id,
            "category": "stirling_ai",
            "summary": operation.description,
            "endpoint": operation.route,
            "requiredScope": operation.required_scope,
            "parametersSchema": operation.input_schema,
        })
        .to_string(),
    )
}

async fn call_ai(
    state: &McpState,
    context: &McpCallContext,
    arguments: &Value,
    operations: &BTreeMap<String, AiCapability>,
) -> Value {
    let Some(operation_id) = operation_argument(arguments) else {
        return tool_error("Missing required argument: operation");
    };
    let Some(operation) = operations.get(operation_id) else {
        return tool_error(&format!(
            "Unknown AI capability '{operation_id}'. The engine manifest may not be loaded yet - retry shortly or confirm the engine is reachable."
        ));
    };
    // Java StirlingAiTool: the manifest's required scope is checked against
    // the caller's real grant after the capability resolves. An API key's
    // static read+write grant reproduces the old apikey-mode behavior
    // (anything outside the two known scopes is refused); an OAuth token must
    // actually carry the scope.
    if !context.has_scope(&operation.required_scope) {
        return tool_error(&format!(
            "Insufficient scope: this capability requires '{}'.",
            operation.required_scope
        ));
    }
    let Some(route) = operation.route.clone() else {
        return tool_error(&format!(
            "Capability '{operation_id}' has no route configured in the engine manifest."
        ));
    };
    let parameters = arguments
        .get("parameters")
        .cloned()
        .unwrap_or_else(|| Value::Object(Map::new()));
    let connection = state.catalog.connection.clone();
    let username = context.auth.username.clone();
    match task::spawn_blocking(move || post_engine(&connection, &route, &parameters, &username))
        .await
    {
        Ok(Ok(response)) => tool_text(&response),
        Ok(Err(error)) => {
            warn!(%error, operation = operation_id, "MCP AI capability request failed");
            tool_error(&format!(
                "Engine request failed for capability '{operation_id}'."
            ))
        }
        Err(error) => {
            warn!(%error, operation = operation_id, "MCP AI capability worker failed");
            tool_error(&format!(
                "Engine request failed for capability '{operation_id}'."
            ))
        }
    }
}

const UPLOAD_FILE_NAME: &str = "upload.bin";

/// Stores an inline base64 file server-side under a fresh owner-scoped job so
/// it can be reused by `fileId` across later `stirling_operation`/
/// `stirling_download` calls. Reuses [`JobManager`] verbatim: no new storage
/// mechanism, no new ownership semantics.
async fn upload_file(state: &McpState, context: &McpCallContext, arguments: &Value) -> Value {
    // Java StirlingUploadTool: storing a file is a write.
    if !context.has_scope(WRITE_SCOPE) {
        return tool_error("Insufficient scope: stirling_upload requires 'mcp.tools.write'.");
    }
    let Some(base64) = text_argument(arguments, "file") else {
        return tool_error("Missing required argument: file (base64-encoded content).");
    };
    let Ok(bytes) = STANDARD.decode(base64) else {
        return tool_error("The 'file' argument is not valid base64.");
    };
    let name = text_argument(arguments, "fileName").unwrap_or("upload.bin");
    let owner = JobOwner::from_auth_context(Some(&context.auth));
    let Ok(submission) = state.job_manager.create_job(owner) else {
        return tool_error("Failed to store the uploaded file.");
    };
    let path = submission.directory.join(UPLOAD_FILE_NAME);
    if tokio::fs::write(&path, &bytes).await.is_err() {
        return tool_error("Failed to store the uploaded file.");
    }
    if state
        .job_manager
        .complete_file(&submission.job_id, &path, name, "application/octet-stream")
        .is_err()
    {
        return tool_error("Failed to store the uploaded file.");
    }
    match state.job_manager.result_file(owner, &submission.job_id) {
        Ok(Some(file)) => tool_text(&format!(
            "Stored '{name}' ({len} bytes) as fileId={file_id}. Pass this fileId to stirling_operation's 'fileId' argument.",
            len = bytes.len(),
            file_id = file.file_id,
        )),
        _ => tool_error("Failed to store the uploaded file."),
    }
}

/// Fetches a stored file's content by `fileId`, inline as base64. Owner
/// isolation comes entirely from [`JobManager::job_file`], which already
/// returns the same "not found" result for a foreign fileId as for a missing
/// one - this function must not distinguish those cases either.
async fn download_file(state: &McpState, context: &McpCallContext, arguments: &Value) -> Value {
    // Java StirlingDownloadTool: fetching a stored file is a read.
    if !context.has_scope(READ_SCOPE) {
        return tool_error("Insufficient scope: stirling_download requires 'mcp.tools.read'.");
    }
    let Some(file_id) = text_argument(arguments, "fileId") else {
        return tool_error("Missing required argument: fileId.");
    };
    let owner = JobOwner::from_auth_context(Some(&context.auth));
    let file = match state.job_manager.job_file(owner, file_id) {
        Ok(Some((_, file))) => file,
        Ok(None) => {
            return tool_error(&format!("Unknown or inaccessible fileId '{file_id}'."));
        }
        Err(_) => return tool_error(&format!("Failed to read fileId '{file_id}'.")),
    };
    if file.file_size > state.config.max_inline_response_bytes {
        return tool_error(&format!(
            "File is {size} bytes, over the inline limit of {limit} bytes. Retrieve it via the Stirling UI/API instead.",
            size = file.file_size,
            limit = state.config.max_inline_response_bytes,
        ));
    }
    let Ok(bytes) = tokio::fs::read(&file.path).await else {
        return tool_error(&format!("Failed to read fileId '{file_id}'."));
    };
    file_result(
        &format!(
            "File {file_id} ({len} bytes) included inline below.",
            len = bytes.len()
        ),
        file_id,
        &file.content_type,
        &bytes,
    )
}

/// Dispatches a real Stirling processing operation (identified by its own API
/// path, e.g. `/api/v1/general/split-pages`) in-process through the same
/// router `pipeline` uses to run a step, with an input resolved from an
/// uploaded `fileId` or inline base64. This tool is a Rust-only extension:
/// Java addresses PDF operations exclusively through the category tools.
async fn run_operation(state: &McpState, context: &McpCallContext, arguments: &Value) -> Value {
    let Some(operation) = text_argument(arguments, "operation") else {
        return tool_error(
            "Missing required argument: operation (the Stirling API path, e.g. /api/v1/general/split-pages).",
        );
    };
    if crate::pipeline::validate_operation_path(operation).is_err()
        || !operation_allowed(&state.config, operation)
    {
        return tool_error(&format!(
            "Operation '{operation}' is not permitted for MCP dispatch."
        ));
    }
    // Rust-only tool, gated like the category tools it parallels: every
    // dispatched Stirling operation is mutating, so it requires the write
    // scope (checked after the operation resolves, matching their order).
    if !context.has_scope(WRITE_SCOPE) {
        return tool_error(&format!(
            "Insufficient scope: this operation requires '{WRITE_SCOPE}'."
        ));
    }
    dispatch_operation(state, context, arguments, operation, operation).await
}

/// The shared dispatch path behind the category tools and `stirling_operation`:
/// resolves the input (`fileId` or inline base64), builds the internal request,
/// runs it through the in-process router, and stores or inlines the result.
/// `label` names the operation in caller-facing messages - the op id for a
/// category tool (matching Java's executor), the full API path for
/// `stirling_operation`.
async fn dispatch_operation(
    state: &McpState,
    context: &McpCallContext,
    arguments: &Value,
    endpoint_path: &str,
    label: &str,
) -> Value {
    let owner = JobOwner::from_auth_context(Some(&context.auth));
    let Some((input_path, input_filename, _scratch)) =
        resolve_operation_input(state, owner, arguments).await
    else {
        return tool_error(
            "This operation needs an input file. Pass 'file' as base64 (recommended for most files), or 'fileId' from stirling_upload for large files.",
        );
    };
    let input_path = match input_path {
        Ok(path) => path,
        Err(message) => return tool_error(&message),
    };

    let parameters = arguments
        .get("parameters")
        .and_then(Value::as_object)
        .cloned()
        .map(|map| map.into_iter().collect::<BTreeMap<_, _>>())
        .unwrap_or_default();
    let pipeline_operation = PipelineOperation {
        operation: endpoint_path.to_owned(),
        parameters,
        file_parameters: BTreeMap::new(),
    };
    let files = [PipelineFile {
        filename: input_filename,
        path: input_path,
        content_type: None,
        origin: None,
    }];
    let Ok(mut request) = crate::pipeline::build_operation_request(
        &pipeline_operation,
        &files,
        &SupportingFiles::new(),
    )
    .await
    else {
        return tool_error(&format!(
            "{label} failed: could not build the internal request."
        ));
    };
    request.extensions_mut().insert(context.auth.clone());

    let response = state
        .dispatch_router
        .clone()
        .oneshot(request)
        .await
        .unwrap_or_else(|never| match never {});
    let status = response.status();
    let headers = response.headers().clone();
    let content_type = headers
        .get(header::CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .unwrap_or_default()
        .to_owned();

    if !status.is_success() {
        let message = crate::pipeline::response_error_message(response).await;
        warn!(operation = label, %status, "MCP operation dispatch failed");
        return tool_error(&format!(
            "{label} failed: HTTP {status}. {}",
            truncate_message(&message, 300)
        ));
    }

    if content_type.starts_with("application/json") {
        let limit = usize::try_from(MAX_ENGINE_RESULT_BYTES).unwrap_or(usize::MAX);
        let Ok(body) = to_bytes(response.into_body(), limit).await else {
            return tool_error(&format!(
                "{label} returned a response that was too large or unreadable."
            ));
        };
        return tool_text(&String::from_utf8_lossy(&body));
    }

    store_operation_result(state, owner, label, &content_type, headers, response).await
}

/// Resolves `stirling_operation`'s input file, either from an owner-scoped
/// `fileId` (already on disk, path reused directly) or a freshly-staged
/// inline base64 payload (written under a request-scoped [`TempDir`] that
/// callers must keep alive until dispatch completes). Returns `None` when
/// neither `fileId` nor `file` was supplied.
async fn resolve_operation_input(
    state: &McpState,
    owner: JobOwner,
    arguments: &Value,
) -> Option<(Result<PathBuf, String>, String, Option<TempDir>)> {
    let file_name = text_argument(arguments, "fileName");
    if let Some(file_id) = text_argument(arguments, "fileId") {
        return Some(match state.job_manager.job_file(owner, file_id) {
            Ok(Some((_, file))) => {
                let name = file_name.map(str::to_owned).unwrap_or(file.file_name);
                (Ok(file.path), name, None)
            }
            Ok(None) => (
                Err(format!(
                    "Unknown or inaccessible fileId '{file_id}'. Re-upload with stirling_upload."
                )),
                String::new(),
                None,
            ),
            Err(_) => (
                Err(format!("Could not read fileId '{file_id}'.")),
                String::new(),
                None,
            ),
        });
    }
    let base64 = text_argument(arguments, "file")?;
    let Ok(bytes) = STANDARD.decode(base64) else {
        return Some((
            Err("The 'file' argument is not valid base64.".to_owned()),
            String::new(),
            None,
        ));
    };
    let Ok(scratch) = TempDir::new() else {
        return Some((
            Err("Could not allocate scratch space for the input file.".to_owned()),
            String::new(),
            None,
        ));
    };
    let path = scratch.path().join("input.bin");
    if tokio::fs::write(&path, &bytes).await.is_err() {
        return Some((
            Err("Could not stage the input file.".to_owned()),
            String::new(),
            None,
        ));
    }
    let name = file_name.unwrap_or("input.pdf").to_owned();
    Some((Ok(path), name, Some(scratch)))
}

/// Streams a `stirling_operation` file result into a fresh owned job (reusing
/// [`crate::pipeline::write_response_to_file`]'s bounded streaming writer, so
/// a large result is never fully buffered in memory), then inlines it when
/// small enough or reports its `fileId` for `stirling_download` otherwise.
async fn store_operation_result(
    state: &McpState,
    owner: JobOwner,
    operation: &str,
    content_type: &str,
    headers: HeaderMap,
    response: Response,
) -> Value {
    let Ok(submission) = state.job_manager.create_job(owner) else {
        return tool_error(&format!(
            "{operation} succeeded but the result could not be stored."
        ));
    };
    // Java's executor falls back to the op id when the upstream response
    // names no file; `operation` is the op id for a category tool and the
    // API path for `stirling_operation`, whose flat tail names the file.
    let filename = crate::pipeline::safe_filename(Some(
        crate::pipeline::response_filename(&headers)
            .as_deref()
            .unwrap_or(operation),
    ));
    let output_path = submission.directory.join(&filename);
    if crate::pipeline::write_response_to_file(response, &output_path)
        .await
        .is_err()
    {
        return tool_error(&format!(
            "{operation} succeeded but the result could not be stored."
        ));
    }
    let content_type = if content_type.is_empty() {
        "application/octet-stream"
    } else {
        content_type
    };
    if state
        .job_manager
        .complete_file(&submission.job_id, &output_path, &filename, content_type)
        .is_err()
    {
        return tool_error(&format!(
            "{operation} succeeded but the result could not be finalized."
        ));
    }
    let Ok(Some(result)) = state.job_manager.result_file(owner, &submission.job_id) else {
        return tool_error(&format!(
            "{operation} succeeded but the result could not be retrieved."
        ));
    };
    let summary = format!(
        "{operation} succeeded. Result: {name} ({size} bytes), fileId={file_id}.",
        name = result.file_name,
        size = result.file_size,
        file_id = result.file_id,
    );
    if result.file_size <= state.config.max_inline_response_bytes
        && let Ok(bytes) = tokio::fs::read(&result.path).await
    {
        return file_result(
            &format!("{summary} The file is included inline below."),
            &result.file_id,
            content_type,
            &bytes,
        );
    }
    tool_text(&format!(
        "{summary} Large result - fetch it with stirling_download {{\"fileId\":\"{}\"}}, or pass this fileId to another operation.",
        result.file_id
    ))
}

fn file_result(summary: &str, file_id: &str, content_type: &str, bytes: &[u8]) -> Value {
    json!({
        "content": [
            {"type": "text", "text": summary},
            {
                "type": "resource",
                "resource": {
                    "uri": format!("stirling://file/{file_id}"),
                    "mimeType": content_type,
                    "blob": STANDARD.encode(bytes),
                },
            },
        ],
    })
}

fn truncate_message(message: &str, max_chars: usize) -> String {
    let truncated: String = message.chars().take(max_chars).collect();
    if truncated.chars().count() < message.chars().count() {
        format!("{truncated}...")
    } else {
        truncated
    }
}

fn fetch_manifest(
    connection: &EngineConnection,
) -> Result<BTreeMap<String, AiCapability>, EngineError> {
    let endpoint = engine_endpoint(connection, CAPABILITIES_PATH)?;
    let client = Client::builder()
        .connect_timeout(Duration::from_secs(5))
        .timeout(Duration::from_secs(10))
        .build()
        .map_err(|_| EngineError::Client)?;
    let mut request = client
        .get(endpoint)
        .header(header::ACCEPT.as_str(), "application/json");
    if let Some(secret) = &connection.shared_secret {
        request = request.header("X-Engine-Auth", secret);
    }
    let response = request.send().map_err(|_| EngineError::Request)?;
    if response.status() != reqwest::StatusCode::OK {
        return Err(EngineError::Status(response.status().as_u16()));
    }
    let body = read_bounded(response, MAX_MANIFEST_BYTES)?;
    parse_manifest(&body)
}

fn post_engine(
    connection: &EngineConnection,
    route: &str,
    parameters: &Value,
    username: &str,
) -> Result<String, EngineError> {
    if !is_safe_relative_route(route) {
        return Err(EngineError::InvalidUrl);
    }
    let endpoint = engine_endpoint(connection, route)?;
    let client = Client::builder()
        .connect_timeout(Duration::from_secs(5).min(connection.timeout))
        .timeout(connection.timeout)
        .build()
        .map_err(|_| EngineError::Client)?;
    let body = serde_json::to_vec(parameters).map_err(|_| EngineError::InvalidManifest)?;
    let mut request = client
        .post(endpoint)
        .header(header::CONTENT_TYPE.as_str(), "application/json")
        .header(header::ACCEPT.as_str(), "application/json")
        .header("X-User-Id", username)
        .body(body);
    if let Some(secret) = &connection.shared_secret {
        request = request.header("X-Engine-Auth", secret);
    }
    let response = request.send().map_err(|_| EngineError::Request)?;
    if !response.status().is_success() {
        return Err(EngineError::Status(response.status().as_u16()));
    }
    let body = read_bounded(response, MAX_ENGINE_RESULT_BYTES)?;
    String::from_utf8(body).map_err(|_| EngineError::ResponseRead)
}

fn engine_endpoint(connection: &EngineConnection, path: &str) -> Result<reqwest::Url, EngineError> {
    let base = connection.base_url.trim().trim_end_matches('/');
    let endpoint =
        reqwest::Url::parse(&format!("{base}{path}")).map_err(|_| EngineError::InvalidUrl)?;
    if !matches!(endpoint.scheme(), "http" | "https")
        || endpoint.username() != ""
        || endpoint.password().is_some()
    {
        return Err(EngineError::InvalidUrl);
    }
    Ok(endpoint)
}

fn read_bounded(
    response: reqwest::blocking::Response,
    maximum: u64,
) -> Result<Vec<u8>, EngineError> {
    if response
        .content_length()
        .is_some_and(|length| length > maximum)
    {
        return Err(EngineError::ResponseTooLarge);
    }
    let mut body = Vec::new();
    response
        .take(maximum + 1)
        .read_to_end(&mut body)
        .map_err(|_| EngineError::ResponseRead)?;
    if body.len() as u64 > maximum {
        return Err(EngineError::ResponseTooLarge);
    }
    Ok(body)
}

fn parse_manifest(body: &[u8]) -> Result<BTreeMap<String, AiCapability>, EngineError> {
    let root = serde_json::from_slice::<Value>(body).map_err(|_| EngineError::InvalidManifest)?;
    let capabilities = root
        .get("capabilities")
        .and_then(Value::as_array)
        .ok_or(EngineError::InvalidManifest)?;
    if capabilities.len() > MAX_CAPABILITIES {
        return Err(EngineError::InvalidManifest);
    }
    let mut operations = BTreeMap::new();
    for entry in capabilities {
        let Some(id) = entry.get("id").and_then(Value::as_str) else {
            continue;
        };
        let Some(input_schema) = entry
            .get("input_schema")
            .filter(|schema| schema.is_object())
        else {
            continue;
        };
        let description = entry
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or(id);
        let required_scope = entry
            .get("required_scope")
            .and_then(Value::as_str)
            .filter(|scope| !scope.trim().is_empty())
            .unwrap_or(WRITE_SCOPE);
        let route = entry.get("route").and_then(Value::as_str);
        if id.len() > MAX_CAPABILITY_ID_BYTES
            || description.len() > MAX_DESCRIPTION_BYTES
            || required_scope.len() > MAX_SCOPE_BYTES
            || route.is_some_and(|route| {
                route.len() > MAX_ROUTE_BYTES || !is_safe_relative_route(route)
            })
            || serde_json::to_vec(input_schema)
                .map_or(true, |schema| schema.len() > MAX_SCHEMA_BYTES)
        {
            continue;
        }
        operations.insert(
            id.to_owned(),
            AiCapability {
                id: id.to_owned(),
                description: description.to_owned(),
                input_schema: input_schema.clone(),
                required_scope: required_scope.to_owned(),
                route: route.map(ToOwned::to_owned),
            },
        );
    }
    Ok(operations)
}

fn is_safe_relative_route(route: &str) -> bool {
    route.starts_with("/api/")
        && !route.starts_with("//")
        && !route.contains("..")
        && !route.contains('@')
        && !route.contains('\\')
        && !route.contains(':')
        && !route.chars().any(|character| character <= ' ')
}

enum AuthFailure {
    Unauthorized,
    Unavailable,
}

/// Authenticates the request in the mounted mode and returns the per-call
/// context (identity + granted scopes), or the finished error response.
async fn authenticate(state: &McpState, headers: &HeaderMap) -> Result<McpCallContext, Response> {
    match &state.oauth {
        None => match authenticate_api_key(&state.store, headers).await {
            Ok(auth) => Ok(McpCallContext::for_api_key(
                auth,
                state.config.scopes_enabled,
            )),
            Err(AuthFailure::Unauthorized) => Err(unauthorized()),
            Err(AuthFailure::Unavailable) => Err(StatusCode::SERVICE_UNAVAILABLE.into_response()),
        },
        Some(verifier) => authenticate_oauth(state, verifier, headers).await,
    }
}

/// The `OAuth2` resource-server path: bearer-JWT validation through
/// [`McpOAuthVerifier`], then Java's `McpUserBindingFilter` account binding.
/// A tokenless request gets the plain RFC 9728 discovery challenge (the
/// normal handshake, logged at debug in Java); a rejected token adds the
/// sanitized reason as `error_description`; a validated token whose subject
/// has no provisioned, enabled Stirling account gets Java's 403
/// `insufficient_account` body.
async fn authenticate_oauth(
    state: &McpState,
    verifier: &Arc<McpOAuthVerifier>,
    headers: &HeaderMap,
) -> Result<McpCallContext, Response> {
    // RFC 9728's path-inserted canonical location for the /mcp resource.
    let metadata_path = format!("{PROTECTED_RESOURCE_METADATA_PATH}{MCP_PATH}");
    let Some(token) = extract_bearer_token(headers) else {
        return Err(oauth_unauthorized(headers, &metadata_path, None));
    };
    let token = Zeroizing::new(token);
    let worker = Arc::clone(verifier);
    let granted = match task::spawn_blocking(move || worker.verify(&token)).await {
        Ok(Ok(granted)) => granted,
        Ok(Err(rejection)) => {
            warn!(reason = %rejection.reason, "MCP rejected bearer token");
            return Err(oauth_unauthorized(
                headers,
                &metadata_path,
                Some(&rejection.reason),
            ));
        }
        Err(error) => {
            warn!(%error, "MCP bearer token verification worker failed");
            return Err(StatusCode::SERVICE_UNAVAILABLE.into_response());
        }
    };
    let Some(username) = granted
        .username_claim_value
        .filter(|value| !value.trim().is_empty())
    else {
        return Err(insufficient_account(&format!(
            "Token is missing the '{}' claim used to map to a Stirling user.",
            verifier.username_claim()
        )));
    };
    let store = Arc::clone(&state.store);
    let correlation = mcp_request_id();
    let subject_for_log = username.replace(['\r', '\n'], " ");
    let bound =
        task::spawn_blocking(move || store.bind_mcp_oauth_user(&username, &correlation)).await;
    let auth = match bound {
        Ok(Ok(auth)) => auth,
        Ok(Err(SecurityError::Storage(_) | SecurityError::Poisoned)) | Err(_) => {
            return Err(StatusCode::SERVICE_UNAVAILABLE.into_response());
        }
        Ok(Err(_)) => {
            warn!(
                subject = subject_for_log,
                "MCP access denied: token subject has no active Stirling account"
            );
            return Err(insufficient_account(
                "MCP access requires a provisioned, enabled Stirling account for this subject.",
            ));
        }
    };
    Ok(McpCallContext {
        auth,
        scopes_enabled: state.config.scopes_enabled,
        granted_scopes: granted.scopes,
    })
}

/// The bearer access token, when the `Authorization` header carries one with
/// a case-insensitive `Bearer` scheme. `X-API-KEY` is deliberately ignored in
/// OAuth mode, matching Java's chain.
fn extract_bearer_token(headers: &HeaderMap) -> Option<String> {
    let authorization = headers.get(header::AUTHORIZATION)?.to_str().ok()?.trim();
    let (scheme, token) = authorization.split_once(' ')?;
    let token = token.trim();
    (scheme.eq_ignore_ascii_case("bearer") && !token.is_empty()).then(|| token.to_owned())
}

/// 401 with the RFC 9728 `WWW-Authenticate` challenge. Java emits the servlet
/// container's default error body via `sendError`; Rust pins a small JSON body
/// instead (documented divergence) — the header is the contract surface.
fn oauth_unauthorized(headers: &HeaderMap, metadata_path: &str, reason: Option<&str>) -> Response {
    let challenge = mcp_oauth::www_authenticate_challenge(headers, metadata_path, reason);
    let mut response = json_response(
        StatusCode::UNAUTHORIZED,
        json!({"error": "unauthorized", "message": "Unauthorized"}),
    );
    if let Ok(value) = HeaderValue::from_str(&challenge) {
        response
            .headers_mut()
            .insert(header::WWW_AUTHENTICATE, value);
    }
    response
}

/// Java `McpUserBindingFilter.reject`: 403 with the `insufficient_account`
/// JSON body.
fn insufficient_account(message: &str) -> Response {
    json_response(
        StatusCode::FORBIDDEN,
        json!({"error": "insufficient_account", "message": message}),
    )
}

async fn authenticate_api_key(
    store: &Arc<SecurityStore>,
    headers: &HeaderMap,
) -> Result<AuthContext, AuthFailure> {
    let key = extract_api_key(headers).ok_or(AuthFailure::Unauthorized)?;
    let key = Zeroizing::new(key);
    let store = Arc::clone(store);
    let correlation = mcp_request_id();
    match task::spawn_blocking(move || store.authenticate_api_key(&key, &correlation)).await {
        Ok(Ok(context)) => Ok(context),
        Ok(Err(SecurityError::Storage(_) | SecurityError::Poisoned)) | Err(_) => {
            Err(AuthFailure::Unavailable)
        }
        Ok(Err(_)) => Err(AuthFailure::Unauthorized),
    }
}

fn extract_api_key(headers: &HeaderMap) -> Option<String> {
    if let Some(key) = headers
        .get("X-API-KEY")
        .and_then(|value| value.to_str().ok())
        .map(str::trim)
        .filter(|key| !key.is_empty())
    {
        return Some(key.to_owned());
    }
    let authorization = headers.get(header::AUTHORIZATION)?.to_str().ok()?.trim();
    let (scheme, key) = authorization.split_once(' ')?;
    if !scheme.eq_ignore_ascii_case("bearer") || key.trim().is_empty() {
        return None;
    }
    Some(key.trim().to_owned())
}

fn mcp_request_id() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static NEXT_ID: AtomicU64 = AtomicU64::new(1);
    format!("mcp-{}", NEXT_ID.fetch_add(1, Ordering::Relaxed))
}

fn is_json_content_type(headers: &HeaderMap) -> bool {
    headers
        .get(header::CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.split(';').next())
        .is_some_and(|value| value.trim().eq_ignore_ascii_case("application/json"))
}

fn declared_body_too_large(headers: &HeaderMap, maximum: usize) -> bool {
    headers
        .get(header::CONTENT_LENGTH)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.parse::<u64>().ok())
        .is_some_and(|length| length > maximum as u64)
}

fn payload_too_large(maximum: usize) -> Response {
    json_response(
        StatusCode::PAYLOAD_TOO_LARGE,
        json!({
            "error": "payload_too_large",
            "message": format!("MCP request body exceeds the configured limit of {maximum} bytes.")
        }),
    )
}

fn unauthorized() -> Response {
    let mut response = json_response(
        StatusCode::UNAUTHORIZED,
        json!({
            "error": "unauthorized",
            "message": "Provide a valid Stirling API key via the X-API-KEY header (or Authorization: Bearer <key>)."
        }),
    );
    response.headers_mut().insert(
        header::WWW_AUTHENTICATE,
        axum::http::HeaderValue::from_static("Bearer realm=\"Stirling MCP (API key)\""),
    );
    response
}

fn rpc_success(id: Value, result: Value) -> Value {
    Value::Object(Map::from_iter([
        ("jsonrpc".to_owned(), Value::String("2.0".to_owned())),
        ("id".to_owned(), id),
        ("result".to_owned(), result),
    ]))
}

fn rpc_failure(id: Value, code: i32, message: &str) -> Value {
    Value::Object(Map::from_iter([
        ("jsonrpc".to_owned(), Value::String("2.0".to_owned())),
        ("id".to_owned(), id),
        ("error".to_owned(), json!({"code":code, "message":message})),
    ]))
}

fn tool_text(text: &str) -> Value {
    json!({"content":[{"type":"text", "text":text}]})
}

fn tool_error(message: &str) -> Value {
    json!({"content":[{"type":"text", "text":message}], "isError":true})
}

/// Trimmed text argument, matching Java's `McpToolSupport.textArg` (used for
/// `file`, `fileName`, and `fileId`).
fn text_argument<'a>(arguments: &'a Value, name: &str) -> Option<&'a str> {
    arguments
        .get(name)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
}

/// The `operation` argument exactly as Java's category/describe/AI tools read
/// it (`JsonNode.asText()` with only a blank check): a blank value counts as
/// missing, but a padded value such as `" rotate-pdf "` is looked up
/// untrimmed - and therefore fails - rather than being trimmed first.
fn operation_argument(arguments: &Value) -> Option<&str> {
    arguments
        .get("operation")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
}

fn json_response(status: StatusCode, body: Value) -> Response {
    (status, axum::Json(body)).into_response()
}

#[cfg(test)]
mod tests {
    use super::{
        AiCapability, AiCapabilityCatalog, EngineConnection, EngineError, MAX_CAPABILITIES,
        McpCallContext, McpState, PDF_OPERATIONS, PdfCategory, call_category, category_tool_schema,
        describe_operation, download_file, extract_api_key, extract_bearer_token,
        is_safe_relative_route, operation_allowed, operation_list_error, parse_manifest,
        run_operation, upload_file,
    };
    use crate::{
        job_manager::JobManager,
        runtime_config::{McpAuthConfig, McpConfig, RuntimeConfig},
        security::{AuthContext, AuthenticationSource, SecurityStore},
    };
    use axum::http::{HeaderMap, HeaderValue, header};
    use base64::{Engine as _, engine::general_purpose::STANDARD};
    use serde_json::json;
    use std::{
        collections::{BTreeMap, BTreeSet},
        io::{self, Read, Write},
        net::TcpListener,
        path::Path,
        sync::{Arc, mpsc},
        thread,
        time::Duration,
    };

    #[test]
    fn manifest_is_bounded_and_unsafe_routes_are_skipped() {
        let manifest = serde_json::json!({"capabilities":[
            {"id":"good","description":"ok","input_schema":{"type":"object"},"required_scope":"","route":"/api/v1/pdf/questions"},
            {"id":"absolute","input_schema":{"type":"object"},"route":"https://evil.test/x"},
            {"id":"escape","input_schema":{"type":"object"},"route":"/api/../secret"},
            {"id":"missing-route","input_schema":{"type":"object"}}
        ]});
        let parsed =
            parse_manifest(&serde_json::to_vec(&manifest).unwrap_or_default()).unwrap_or_default();
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed["good"].required_scope, "mcp.tools.write");
        assert!(parsed["missing-route"].route.is_none());
        assert!(!is_safe_relative_route("//evil.test/x"));
        assert!(!is_safe_relative_route("/api/v1/x y"));
    }

    #[test]
    fn manifest_rejects_excessive_entry_count() {
        let capabilities = (0..=MAX_CAPABILITIES)
            .map(|index| serde_json::json!({"id":index.to_string(),"input_schema":{}}))
            .collect::<Vec<_>>();
        let error = parse_manifest(
            &serde_json::to_vec(&serde_json::json!({"capabilities":capabilities}))
                .unwrap_or_default(),
        );
        assert!(matches!(error, Err(EngineError::InvalidManifest)));
    }

    #[test]
    fn api_key_header_wins_and_bearer_is_case_insensitive() {
        let mut headers = HeaderMap::new();
        headers.insert("X-API-KEY", HeaderValue::from_static("header-key"));
        headers.insert(
            header::AUTHORIZATION,
            HeaderValue::from_static("bearer bearer-key"),
        );
        assert_eq!(extract_api_key(&headers).as_deref(), Some("header-key"));
        headers.remove("X-API-KEY");
        assert_eq!(extract_api_key(&headers).as_deref(), Some("bearer-key"));
    }

    #[test]
    fn allow_and_block_filters_match_java_precedence() {
        let mut config = McpConfig {
            enabled: true,
            scopes_enabled: true,
            engine_capability_refresh_minutes: 5,
            allowed_operations: vec!["allowed".to_owned()],
            blocked_operations: Vec::new(),
            max_request_bytes: 1024,
            max_inline_response_bytes: 1024,
            auth: McpAuthConfig {
                mode: "apikey".to_owned(),
                issuer_uri: String::new(),
                jwks_uri: String::new(),
                resource_id: String::new(),
                accepted_audiences: Vec::new(),
                username_claim: "sub".to_owned(),
                require_existing_account: true,
            },
        };
        assert!(operation_allowed(&config, "allowed"));
        assert!(!operation_allowed(&config, "other"));
        config.blocked_operations.push("allowed".to_owned());
        assert!(!operation_allowed(&config, "allowed"));
    }

    #[test]
    fn engine_requests_send_the_shared_secret_and_only_the_provided_parameters()
    -> Result<(), Box<dyn std::error::Error>> {
        let manifest = json!({"capabilities":[{
            "id":"agent-draft",
            "input_schema":{"type":"object"},
            "route":"/api/v1/agents/draft"
        }]})
        .to_string();
        let (manifest_url, manifest_request, manifest_server) = mock_http_response(200, &manifest)?;
        let connection = EngineConnection {
            enabled: true,
            base_url: manifest_url,
            timeout: Duration::from_secs(1),
            shared_secret: Some("secret".to_owned()),
        };
        let fetched = super::fetch_manifest(&connection).unwrap_or_default();
        assert!(fetched.contains_key("agent-draft"));
        let request = manifest_request
            .recv_timeout(Duration::from_secs(2))
            .unwrap_or_default();
        assert!(request.starts_with("GET /api/v1/agents/capabilities HTTP/1.1\r\n"));
        assert!(
            request
                .to_ascii_lowercase()
                .contains("x-engine-auth: secret\r\n")
        );
        let _ = manifest_server.join();

        let (post_url, post_request, post_server) =
            mock_http_response(200, r#"{"accepted":true}"#)?;
        let connection = EngineConnection {
            enabled: true,
            base_url: post_url,
            timeout: Duration::from_secs(1),
            shared_secret: Some("secret".to_owned()),
        };
        let response = super::post_engine(
            &connection,
            "/api/v1/agents/draft",
            &json!({"prompt":"draft","fileId":"nested-only"}),
            "Canonical.User@Example.Test",
        )
        .unwrap_or_default();
        assert_eq!(response, r#"{"accepted":true}"#);
        let request = post_request
            .recv_timeout(Duration::from_secs(2))
            .unwrap_or_default();
        assert!(request.starts_with("POST /api/v1/agents/draft HTTP/1.1\r\n"));
        assert!(
            request
                .to_ascii_lowercase()
                .contains("x-engine-auth: secret\r\n")
        );
        assert!(
            request
                .to_ascii_lowercase()
                .contains("x-user-id: canonical.user@example.test\r\n")
        );
        assert!(request.ends_with(r#"{"fileId":"nested-only","prompt":"draft"}"#));
        let _ = post_server.join();
        Ok(())
    }

    #[tokio::test]
    async fn failed_refresh_retains_last_known_good_manifest_and_disabled_engine_clears_it()
    -> Result<(), Box<dyn std::error::Error>> {
        let (url, request, server) = mock_http_response(500, r#"{"error":"unavailable"}"#)?;
        let catalog = AiCapabilityCatalog::new(
            EngineConnection {
                enabled: true,
                base_url: url,
                timeout: Duration::from_secs(1),
                shared_secret: None,
            },
            1,
        );
        if let Ok(mut cache) = catalog.cache.lock() {
            cache.operations = BTreeMap::from([(
                "cached-agent".to_owned(),
                AiCapability {
                    id: "cached-agent".to_owned(),
                    description: "last known good".to_owned(),
                    input_schema: json!({"type":"object"}),
                    required_scope: "mcp.tools.write".to_owned(),
                    route: Some("/api/v1/agents/draft".to_owned()),
                },
            )]);
            cache.last_attempt = None;
        }
        assert!(catalog.snapshot().await.contains_key("cached-agent"));
        let _ = request.recv_timeout(Duration::from_secs(2));
        let _ = server.join();

        let disabled = AiCapabilityCatalog::new(
            EngineConnection {
                enabled: false,
                base_url: "http://127.0.0.1:1".to_owned(),
                timeout: Duration::from_secs(1),
                shared_secret: None,
            },
            1,
        );
        let cached = catalog.snapshot().await;
        if let Ok(mut cache) = disabled.cache.lock() {
            cache.operations = cached;
        }
        assert!(disabled.snapshot().await.is_empty());
        assert!(
            disabled
                .cache
                .lock()
                .map(|cache| cache.operations.is_empty())
                .unwrap_or(false)
        );
        Ok(())
    }

    #[test]
    fn pdf_operation_catalog_matches_java_extract_op_id_semantics() {
        assert!(!PDF_OPERATIONS.is_empty());
        // Op ids are flat URL tails only: nested and parametrised tails are
        // skipped, exactly like Java's extractOpId.
        assert!(
            PDF_OPERATIONS
                .values()
                .all(|operation| !operation.id.contains('/') && !operation.id.contains('{'))
        );
        // Every convert endpoint is nested, so the convert category is empty.
        assert!(
            !PDF_OPERATIONS
                .values()
                .any(|operation| operation.category == PdfCategory::Convert)
        );
        let rotate = PDF_OPERATIONS.get("rotate-pdf");
        assert_eq!(
            rotate.map(|operation| operation.category),
            Some(PdfCategory::Pages)
        );
        assert_eq!(
            rotate.map(|operation| operation.endpoint_path.as_str()),
            Some("/api/v1/general/rotate-pdf")
        );
        // No model description in the catalog: Java's prettified-id fallback.
        assert_eq!(
            rotate.map(|operation| operation.summary.as_str()),
            Some("rotate pdf")
        );
        assert_eq!(
            PDF_OPERATIONS.get("compress-pdf").map(|op| op.category),
            Some(PdfCategory::Misc)
        );
        assert_eq!(
            PDF_OPERATIONS.get("add-password").map(|op| op.category),
            Some(PdfCategory::Security)
        );
    }

    #[test]
    fn supplement_restores_the_flat_operations_the_ai_catalog_excludes() {
        // The AI catalog's generator excludes these flat POST paths for
        // AI-engine reasons, but Java's McpToolCatalog has no exclusion list
        // and indexes every one of them; the MCP supplement restores them.
        let expected = [
            (PdfCategory::Security, "cert-sign"),
            (PdfCategory::Security, "get-info-on-pdf"),
            (PdfCategory::Security, "verify-pdf"),
            (PdfCategory::Security, "validate-signature"),
            (PdfCategory::Misc, "list-attachments"),
            (PdfCategory::Misc, "show-javascript"),
            (PdfCategory::Misc, "decompress-pdf"),
            (PdfCategory::Misc, "add-image"),
            (PdfCategory::Misc, "add-attachments"),
            (PdfCategory::Pages, "extract-bookmarks"),
            (PdfCategory::Pages, "overlay-pdfs"),
        ];
        for (category, id) in expected {
            let operation = PDF_OPERATIONS.get(id);
            assert_eq!(
                operation.map(|operation| operation.category),
                Some(category),
                "supplement operation {id} is missing or miscategorised"
            );
            assert_eq!(
                operation.map(|operation| operation.endpoint_path.as_str()),
                Some(format!("{}{id}", category.url_prefix()).as_str())
            );
            assert!(operation.is_some_and(|operation| operation.parameters_schema.is_object()));
        }
    }

    #[test]
    fn category_schema_and_operation_list_error_match_java_text()
    -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let state = stub_state(directory.path(), axum::Router::new(), 1024)?;

        let pages = category_tool_schema(&state, PdfCategory::Pages);
        assert_eq!(pages["type"], "object");
        assert_eq!(pages["additionalProperties"], false);
        assert_eq!(pages["required"], json!(["operation"]));
        let description = pages["properties"]["operation"]["description"]
            .as_str()
            .unwrap_or_default();
        assert!(description.starts_with(
            "Operation id from this category. Call stirling_describe_operation first to learn the exact parameters schema. Available operations:\n- "
        ));
        assert!(description.contains("\n- rotate-pdf - rotate pdf"));
        assert!(
            pages["properties"]["operation"]["enum"]
                .as_array()
                .is_some_and(|ids| ids
                    .windows(2)
                    .all(|pair| pair[0].as_str().unwrap_or_default()
                        < pair[1].as_str().unwrap_or_default()))
        );

        // An empty category keeps the base text with no trailing newline.
        let convert = category_tool_schema(&state, PdfCategory::Convert);
        assert_eq!(convert["properties"]["operation"]["enum"], json!([]));
        assert!(
            convert["properties"]["operation"]["description"]
                .as_str()
                .is_some_and(|text| text.ends_with("Available operations:"))
        );

        let unknown = operation_list_error(&state, PdfCategory::Pages, Some("nope"));
        assert_eq!(unknown["isError"], true);
        let unknown_text = unknown["content"][0]["text"].as_str().unwrap_or_default();
        assert!(unknown_text.starts_with(
            "Unknown or disabled operation 'nope' for stirling_pages. Available operations:\n- "
        ));
        assert!(unknown_text.ends_with("\nRe-call this tool with a valid 'operation'."));

        let missing = operation_list_error(&state, PdfCategory::Convert, None);
        assert_eq!(
            missing["content"][0]["text"],
            "Missing required argument 'operation' for stirling_convert. No operations are currently available in this category."
        );
        Ok(())
    }

    #[test]
    fn describe_resolves_supplement_operations() -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let state = stub_state(directory.path(), axum::Router::new(), 1024)?;
        let described =
            describe_operation(&state, &json!({"operation": "cert-sign"}), &BTreeMap::new());
        assert_eq!(described.get("isError"), None);
        let payload: serde_json::Value = serde_json::from_str(
            described["content"][0]["text"]
                .as_str()
                .ok_or("describe result was not text")?,
        )?;
        assert_eq!(payload["operation"], "cert-sign");
        assert_eq!(payload["category"], "stirling_security");
        assert_eq!(payload["endpoint"], "/api/v1/security/cert-sign");
        assert_eq!(payload["requiredScope"], "mcp.tools.write");
        assert_eq!(payload["parametersSchema"]["type"], "object");
        Ok(())
    }

    #[tokio::test]
    async fn operation_argument_is_looked_up_untrimmed_like_java()
    -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let state = stub_state(directory.path(), axum::Router::new(), 1024)?;
        let context = test_context();

        // Java reads the id via JsonNode.asText() without trimming, so a
        // padded id fails the lookup and is quoted verbatim in the error.
        let padded = call_category(
            &state,
            &context,
            PdfCategory::Pages,
            &json!({"operation": " rotate-pdf "}),
        )
        .await;
        assert_eq!(padded["isError"], true);
        assert!(padded["content"][0]["text"].as_str().is_some_and(|text| {
            text.starts_with("Unknown or disabled operation ' rotate-pdf ' for stirling_pages.")
        }));

        // A blank id counts as missing, exactly like Java's isBlank check.
        let blank = call_category(
            &state,
            &context,
            PdfCategory::Pages,
            &json!({"operation": "   "}),
        )
        .await;
        assert!(blank["content"][0]["text"].as_str().is_some_and(|text| {
            text.starts_with("Missing required argument 'operation' for stirling_pages.")
        }));

        // stirling_describe_operation shares the same untrimmed rule.
        let described = describe_operation(
            &state,
            &json!({"operation": " rotate-pdf "}),
            &BTreeMap::new(),
        );
        assert_eq!(
            described["content"][0]["text"],
            "Unknown or disabled operation:  rotate-pdf "
        );
        Ok(())
    }

    #[tokio::test]
    async fn category_dispatch_reports_json_file_oversized_and_unrouted_results()
    -> Result<(), Box<dyn std::error::Error>> {
        use axum::routing::post;
        let context = test_context();
        let arguments = json!({
            "operation": "rotate-pdf",
            "file": STANDARD.encode(b"fake input bytes"),
        });

        // A JSON response is a structured report returned inline as text.
        let directory = tempfile::tempdir()?;
        let json_router = axum::Router::new().route(
            "/api/v1/general/rotate-pdf",
            post(|| async {
                (
                    [(header::CONTENT_TYPE, "application/json")],
                    r#"{"report":true}"#,
                )
            }),
        );
        let state = stub_state(directory.path(), json_router, 1024 * 1024)?;
        let result = call_category(&state, &context, PdfCategory::Pages, &arguments).await;
        assert_eq!(result.get("isError"), None);
        assert_eq!(result["content"][0]["text"], r#"{"report":true}"#);

        // A small binary response is stored and inlined as a resource block.
        let directory = tempfile::tempdir()?;
        let file_router = axum::Router::new().route(
            "/api/v1/general/rotate-pdf",
            post(|| async { ([(header::CONTENT_TYPE, "application/pdf")], vec![7_u8; 64]) }),
        );
        let state = stub_state(directory.path(), file_router.clone(), 1024 * 1024)?;
        let result = call_category(&state, &context, PdfCategory::Pages, &arguments).await;
        assert_eq!(result.get("isError"), None);
        let text = result["content"][0]["text"].as_str().unwrap_or_default();
        // No Content-Disposition upstream: the op id names the file, exactly
        // like Java's buildResult fallback to meta.id().
        assert!(text.starts_with("rotate-pdf succeeded. Result: rotate-pdf (64 bytes)"));
        assert!(text.contains("The file is included inline below."));
        assert_eq!(
            result["content"][1]["resource"]["mimeType"],
            "application/pdf"
        );
        let blob = result["content"][1]["resource"]["blob"]
            .as_str()
            .unwrap_or_default();
        assert_eq!(STANDARD.decode(blob)?, vec![7_u8; 64]);

        // Over the inline limit: fileId-only message, no resource block.
        let directory = tempfile::tempdir()?;
        let state = stub_state(directory.path(), file_router, 8)?;
        let result = call_category(&state, &context, PdfCategory::Pages, &arguments).await;
        assert_eq!(result.get("isError"), None);
        assert_eq!(result["content"].as_array().map(Vec::len), Some(1));
        assert!(
            result["content"][0]["text"]
                .as_str()
                .is_some_and(|text| text
                    .contains("Large result - fetch it with stirling_download"))
        );

        // A catalog op whose route the Rust router does not implement fails
        // at dispatch with the op's HTTP status (documented in the contract).
        let directory = tempfile::tempdir()?;
        let state = stub_state(directory.path(), axum::Router::new(), 1024)?;
        let result = call_category(&state, &context, PdfCategory::Pages, &arguments).await;
        assert_eq!(result["isError"], true);
        assert!(
            result["content"][0]["text"]
                .as_str()
                .is_some_and(|text| text.starts_with("rotate-pdf failed: HTTP 404"))
        );
        Ok(())
    }

    #[tokio::test]
    async fn per_scope_gating_matches_java_tool_checks_and_order()
    -> Result<(), Box<dyn std::error::Error>> {
        let directory = tempfile::tempdir()?;
        let state = stub_state(directory.path(), axum::Router::new(), 1024)?;

        // Every PDF operation is a write; a read-only caller is refused with
        // Java's AbstractCategoryTool message, AFTER the operation resolves.
        let read_only = scoped_context(&["mcp.tools.read"]);
        let refused = call_category(
            &state,
            &read_only,
            PdfCategory::Pages,
            &json!({"operation": "rotate-pdf"}),
        )
        .await;
        assert_eq!(refused["isError"], true);
        assert_eq!(
            refused["content"][0]["text"],
            "Insufficient scope: this operation requires 'mcp.tools.write'."
        );
        // Java's order: an unknown operation reports the operation-list error,
        // never the scope error, even for an unprivileged caller.
        let unknown = call_category(
            &state,
            &read_only,
            PdfCategory::Pages,
            &json!({"operation": "nope"}),
        )
        .await;
        assert!(unknown["content"][0]["text"].as_str().is_some_and(|text| {
            text.starts_with("Unknown or disabled operation 'nope' for stirling_pages.")
        }));

        let upload = upload_file(
            &state,
            &read_only,
            &json!({"file": STANDARD.encode(b"bytes")}),
        )
        .await;
        assert_eq!(
            upload["content"][0]["text"],
            "Insufficient scope: stirling_upload requires 'mcp.tools.write'."
        );

        let write_only = scoped_context(&["mcp.tools.write"]);
        let download = download_file(&state, &write_only, &json!({"fileId": "abc"})).await;
        assert_eq!(
            download["content"][0]["text"],
            "Insufficient scope: stirling_download requires 'mcp.tools.read'."
        );

        let operation = run_operation(
            &state,
            &read_only,
            &json!({"operation": "/api/v1/general/rotate-pdf"}),
        )
        .await;
        assert_eq!(
            operation["content"][0]["text"],
            "Insufficient scope: this operation requires 'mcp.tools.write'."
        );

        // mcp.scopesEnabled=false disables the gate entirely (Java hasScope).
        let ungated = McpCallContext {
            auth: test_auth_context(),
            scopes_enabled: false,
            granted_scopes: BTreeSet::new(),
        };
        let download = download_file(&state, &ungated, &json!({"fileId": "abc"})).await;
        assert!(
            download["content"][0]["text"]
                .as_str()
                .is_some_and(|text| { text.starts_with("Unknown or inaccessible fileId") })
        );
        Ok(())
    }

    #[test]
    fn bearer_token_extraction_ignores_api_key_headers() {
        let mut headers = HeaderMap::new();
        headers.insert("X-API-KEY", HeaderValue::from_static("some-api-key"));
        assert_eq!(extract_bearer_token(&headers), None);
        headers.insert(
            header::AUTHORIZATION,
            HeaderValue::from_static("bEaReR the-token"),
        );
        assert_eq!(extract_bearer_token(&headers).as_deref(), Some("the-token"));
        headers.insert(header::AUTHORIZATION, HeaderValue::from_static("Basic xyz"));
        assert_eq!(extract_bearer_token(&headers), None);
        headers.insert(header::AUTHORIZATION, HeaderValue::from_static("Bearer  "));
        assert_eq!(extract_bearer_token(&headers), None);
    }

    fn stub_state(
        directory: &Path,
        dispatch_router: axum::Router,
        max_inline_response_bytes: u64,
    ) -> Result<McpState, Box<dyn std::error::Error>> {
        Ok(McpState {
            config: McpConfig {
                enabled: true,
                scopes_enabled: true,
                engine_capability_refresh_minutes: 5,
                allowed_operations: Vec::new(),
                blocked_operations: Vec::new(),
                max_request_bytes: 1024 * 1024,
                max_inline_response_bytes,
                auth: McpAuthConfig {
                    mode: "apikey".to_owned(),
                    issuer_uri: String::new(),
                    jwks_uri: String::new(),
                    resource_id: String::new(),
                    accepted_audiences: Vec::new(),
                    username_claim: "sub".to_owned(),
                    require_existing_account: true,
                },
            },
            store: Arc::new(SecurityStore::open(&directory.join("security.db"))?),
            catalog: Arc::new(AiCapabilityCatalog::new(
                EngineConnection {
                    enabled: false,
                    base_url: "http://127.0.0.1:1".to_owned(),
                    timeout: Duration::from_secs(1),
                    shared_secret: None,
                },
                1,
            )),
            job_manager: Arc::new(JobManager::new()),
            dispatch_router,
            runtime_config: Arc::new(RuntimeConfig::from_files(
                directory.join("settings.yml"),
                directory.join("local.yml"),
            )),
            oauth: None,
        })
    }

    fn test_context() -> McpCallContext {
        McpCallContext::for_api_key(test_auth_context(), true)
    }

    fn test_auth_context() -> AuthContext {
        AuthContext {
            user_id: 7,
            username: "unit@example.test".to_owned(),
            authentication_source: AuthenticationSource::ApiKey,
            authentication_type: "apikey".to_owned(),
            roles: BTreeSet::new(),
            team_id: None,
            permissions: BTreeSet::new(),
            external_subject: None,
            force_password_change: false,
            session_id: "session".to_owned(),
            correlation_id: "correlation".to_owned(),
        }
    }

    /// A caller granted exactly `scopes`, as an OAuth token's `scope` claim
    /// would produce.
    fn scoped_context(scopes: &[&str]) -> McpCallContext {
        McpCallContext {
            auth: test_auth_context(),
            scopes_enabled: true,
            granted_scopes: scopes.iter().map(|scope| (*scope).to_owned()).collect(),
        }
    }

    fn mock_http_response(
        status: u16,
        body: &str,
    ) -> io::Result<(String, mpsc::Receiver<String>, thread::JoinHandle<()>)> {
        let listener = TcpListener::bind("127.0.0.1:0")?;
        let address = listener.local_addr()?;
        let body = body.to_owned();
        let (request_tx, request_rx) = mpsc::channel();
        let server = thread::spawn(move || {
            let Ok((mut stream, _)) = listener.accept() else {
                return;
            };
            let _ = stream.set_read_timeout(Some(Duration::from_secs(2)));
            let mut request = Vec::new();
            let mut expected_length = None;
            loop {
                let mut chunk = [0_u8; 4096];
                let Ok(read) = stream.read(&mut chunk) else {
                    break;
                };
                if read == 0 {
                    break;
                }
                request.extend_from_slice(&chunk[..read]);
                if expected_length.is_none()
                    && let Some(header_end) =
                        request.windows(4).position(|part| part == b"\r\n\r\n")
                {
                    let headers = String::from_utf8_lossy(&request[..header_end]);
                    let length = headers.lines().find_map(|line| {
                        let (name, value) = line.split_once(':')?;
                        name.eq_ignore_ascii_case("content-length")
                            .then(|| value.trim().parse::<usize>().ok())
                            .flatten()
                    });
                    expected_length = Some((header_end + 4, length.unwrap_or(0)));
                }
                if expected_length
                    .is_some_and(|(header_end, length)| request.len() >= header_end + length)
                {
                    break;
                }
            }
            let _ = request_tx.send(String::from_utf8_lossy(&request).into_owned());
            let reason = if status == 200 { "OK" } else { "Error" };
            let response = format!(
                "HTTP/1.1 {status} {reason}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
                body.len()
            );
            let _ = stream.write_all(response.as_bytes());
        });
        Ok((format!("http://{address}"), request_rx, server))
    }
}
