//! Bounded SMTP email delivery for the legacy attachment endpoint.

use std::{sync::Arc, time::Duration};

use axum::{
    Router,
    extract::{Extension, Multipart},
    http::{StatusCode, header},
    response::{IntoResponse, Response},
    routing::post,
};
use lettre::{
    AsyncSmtpTransport, AsyncTransport, Message, Tokio1Executor,
    message::{Attachment, Mailbox, MultiPart, SinglePart, header::ContentType},
    transport::smtp::{
        authentication::Credentials,
        client::{Tls, TlsParameters},
    },
};
use thiserror::Error;

use crate::{
    runtime_config::{SmtpHostnameVerification, SmtpMailConfig, SmtpTransportSecurity},
    security::SecurityAuditContext,
};

pub(crate) const SEND_EMAIL_PATH: &str = "/api/v1/general/send-email";

const MAX_ADDRESS_BYTES: usize = 320;
const MAX_SUBJECT_BYTES: usize = 4 * 1024;
const MAX_BODY_BYTES: usize = 1024 * 1024;
const MAX_FILENAME_BYTES: usize = 255;
const MAX_ATTACHMENT_BYTES: usize = 100 * 1024 * 1024;
const SMTP_TIMEOUT: Duration = Duration::from_secs(30);
const DEFAULT_SUBJECT: &str = "Stirling Software PDF Notification";
const DEFAULT_BODY: &str = "This message was automatically generated by Stirling-PDF, an innovative solution from Stirling Software. For more information, visit our <a href=\"https://stirling-software.com\">website</a>.<br><br>Please do not reply directly to this email.";

pub(crate) struct SmtpMailService {
    config: SmtpMailConfig,
}

struct OutgoingMail {
    recipient: Mailbox,
    subject: String,
    body: String,
    attachment: Option<MailAttachment>,
}

struct MailAttachment {
    filename: String,
    content_type: ContentType,
    bytes: Vec<u8>,
}

#[derive(Debug, Error)]
pub(crate) enum MailError {
    #[error("Invalid Addresses")]
    InvalidAddress,
    #[error("An attachment is required to send the email.")]
    MissingAttachment,
    #[error("Email request exceeds the supported size")]
    InputTooLarge,
    #[error("Email request contains invalid text")]
    InvalidText,
    #[error("SMTP configuration is incomplete")]
    InvalidConfiguration,
    #[error("Insecure SMTP certificate policy is not supported")]
    InsecureTlsPolicy,
    #[error("Could not construct the email message")]
    Message,
    #[error("SMTP delivery failed")]
    Delivery,
}

impl SmtpMailService {
    pub(crate) fn new(config: SmtpMailConfig) -> Self {
        Self { config }
    }

    async fn send(&self, outgoing: OutgoingMail) -> Result<(), MailError> {
        let message = self.build_message(outgoing)?;
        let transport = self.transport()?;
        transport
            .send(message)
            .await
            .map_err(|_| MailError::Delivery)?;
        Ok(())
    }

    pub(crate) async fn send_invite_link(
        &self,
        recipient: &str,
        invite_url: &str,
        expires_at: &str,
    ) -> Result<(), MailError> {
        let body = invite_link_body(invite_url, expires_at)?;
        self.send(OutgoingMail {
            recipient: parse_mailbox(recipient)?,
            subject: "You've been invited to Stirling PDF".to_owned(),
            body,
            attachment: None,
        })
        .await
    }

    pub(crate) async fn send_user_invite(
        &self,
        recipient: &str,
        username: &str,
        temporary_password: &str,
        login_url: &str,
    ) -> Result<(), MailError> {
        let body = user_invite_body(username, temporary_password, login_url)?;
        self.send(OutgoingMail {
            recipient: parse_mailbox(recipient)?,
            subject: "Welcome to Stirling PDF".to_owned(),
            body,
            attachment: None,
        })
        .await
    }

    pub(crate) async fn send_password_changed(
        &self,
        recipient: &str,
        username: &str,
        temporary_password: Option<&str>,
        login_url: &str,
    ) -> Result<(), MailError> {
        let body = password_changed_body(username, temporary_password, login_url)?;
        self.send(OutgoingMail {
            recipient: parse_mailbox(recipient)?,
            subject: "Your Stirling PDF password has been updated".to_owned(),
            body,
            attachment: None,
        })
        .await
    }

    fn build_message(&self, outgoing: OutgoingMail) -> Result<Message, MailError> {
        let sender = parse_mailbox(&self.config.from)?;
        let builder = Message::builder()
            .from(sender)
            .to(outgoing.recipient)
            .subject(outgoing.subject);
        let html = SinglePart::builder()
            .header(ContentType::TEXT_HTML)
            .body(outgoing.body);
        match outgoing.attachment {
            Some(attachment) => builder.multipart(
                MultiPart::mixed().singlepart(html).singlepart(
                    Attachment::new(attachment.filename)
                        .body(attachment.bytes, attachment.content_type),
                ),
            ),
            None => builder.singlepart(html),
        }
        .map_err(|_| MailError::Message)
    }

    fn transport(&self) -> Result<AsyncSmtpTransport<Tokio1Executor>, MailError> {
        let host = self.config.host.trim();
        if host.is_empty() || self.config.port == 0 {
            return Err(MailError::InvalidConfiguration);
        }
        self.validate_tls_policy(host)?;

        let mut builder = AsyncSmtpTransport::<Tokio1Executor>::builder_dangerous(host)
            .port(self.config.port)
            .timeout(Some(SMTP_TIMEOUT));
        let tls = match self.config.transport_security {
            SmtpTransportSecurity::Plaintext => None,
            SmtpTransportSecurity::OpportunisticStartTls => {
                Some(Tls::Opportunistic(tls_parameters(host)?))
            }
            SmtpTransportSecurity::RequiredStartTls => Some(Tls::Required(tls_parameters(host)?)),
            SmtpTransportSecurity::ImplicitTls => Some(Tls::Wrapper(tls_parameters(host)?)),
        };
        if let Some(tls) = tls {
            builder = builder.tls(tls);
        }
        if self.config.username.is_some() || self.config.password.is_some() {
            builder = builder.credentials(Credentials::new(
                self.config.username.clone().unwrap_or_default(),
                self.config
                    .password
                    .as_ref()
                    .map(|password| password.to_string())
                    .unwrap_or_default(),
            ));
        }
        Ok(builder.build())
    }

    fn validate_tls_policy(&self, host: &str) -> Result<(), MailError> {
        if self.config.hostname_verification == SmtpHostnameVerification::Disabled {
            return Err(MailError::InsecureTlsPolicy);
        }
        if self
            .config
            .ssl_trust
            .as_deref()
            .is_some_and(|trusted| trusted.trim() == "*" || !trusted.eq_ignore_ascii_case(host))
        {
            return Err(MailError::InsecureTlsPolicy);
        }
        Ok(())
    }
}

pub(crate) fn routes(service: Arc<SmtpMailService>) -> Router {
    Router::new()
        .route(SEND_EMAIL_PATH, post(send_email_with_attachment))
        .layer(Extension(service))
}

async fn send_email_with_attachment(
    Extension(service): Extension<Arc<SmtpMailService>>,
    multipart: Multipart,
) -> Response {
    let outgoing = match read_request(multipart).await {
        Ok(outgoing) => outgoing,
        Err(error) => return mail_error_response(&error),
    };
    match service.send(outgoing).await {
        Ok(()) => text_response(StatusCode::OK, "Email sent successfully"),
        Err(error) => mail_error_response(&error),
    }
}

async fn read_request(mut multipart: Multipart) -> Result<OutgoingMail, MailError> {
    let mut recipient = None;
    let mut subject = None;
    let mut body = None;
    let mut attachment = None;

    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|_| MailError::InvalidText)?
    {
        match field.name().unwrap_or_default() {
            "to" => recipient = Some(read_text(field, "to", MAX_ADDRESS_BYTES).await?),
            "subject" => {
                subject = Some(read_text(field, "subject", MAX_SUBJECT_BYTES).await?);
            }
            "body" => body = Some(read_text(field, "body", MAX_BODY_BYTES).await?),
            "fileInput" => {
                let filename = safe_attachment_filename(field.file_name())?;
                let audit_content_type = field.content_type().map(ToOwned::to_owned);
                let content_type = field
                    .content_type()
                    .and_then(|value| ContentType::parse(value).ok())
                    .unwrap_or(
                        ContentType::parse("application/octet-stream")
                            .map_err(|_| MailError::Message)?,
                    );
                let bytes = field.bytes().await.map_err(|_| MailError::InvalidText)?;
                SecurityAuditContext::record_current_file_bytes(
                    &filename,
                    u64::try_from(bytes.len()).unwrap_or(u64::MAX),
                    audit_content_type.as_deref(),
                    &bytes,
                );
                if bytes.is_empty() {
                    return Err(MailError::MissingAttachment);
                }
                if bytes.len() > MAX_ATTACHMENT_BYTES {
                    return Err(MailError::InputTooLarge);
                }
                attachment = Some(MailAttachment {
                    filename,
                    content_type,
                    bytes: bytes.to_vec(),
                });
            }
            _ => {}
        }
    }

    let recipient = recipient.ok_or(MailError::InvalidAddress)?;
    Ok(OutgoingMail {
        recipient: parse_mailbox(&recipient)?,
        subject: subject.unwrap_or_else(|| DEFAULT_SUBJECT.to_owned()),
        body: body.unwrap_or_else(|| DEFAULT_BODY.to_owned()),
        attachment: Some(attachment.ok_or(MailError::MissingAttachment)?),
    })
}

fn invite_link_body(invite_url: &str, expires_at: &str) -> Result<String, MailError> {
    if invite_url.is_empty()
        || invite_url.len() > MAX_BODY_BYTES / 4
        || expires_at.len() > MAX_SUBJECT_BYTES
        || invite_url.chars().any(char::is_control)
        || expires_at.chars().any(char::is_control)
    {
        return Err(MailError::InvalidText);
    }
    let invite_url = escape_html(invite_url);
    let expires_at = escape_html(expires_at);
    let body = format!(
        r#"<html><body style="margin: 0; padding: 0;">
<div style="font-family: Arial, sans-serif; background-color: #f8f9fa; padding: 20px;">
  <div style="max-width: 600px; margin: auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; border: 1px solid #e0e0e0;">
    <div style="text-align: center; padding: 20px; background-color: #222;">
      <img src="https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/docs/stirling-transparent.svg" alt="Stirling PDF" style="max-height: 60px;">
    </div>
    <div style="padding: 30px; color: #333;">
      <h2 style="color: #222; margin-top: 0;">Welcome to Stirling PDF!</h2>
      <p>Hi there,</p>
      <p>You have been invited to join the Stirling PDF workspace. Click the button below to set up your account:</p>
      <div style="text-align: center; margin: 30px 0;">
        <a href="{invite_url}" style="display: inline-block; background-color: #007bff; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 5px; font-weight: bold;">Accept Invitation</a>
      </div>
      <p style="font-size: 14px; color: #666;">Or copy and paste this link in your browser:</p>
      <div style="background-color: #f8f9fa; padding: 12px; margin: 15px 0; border-radius: 4px; word-break: break-all; font-size: 13px; color: #555;">
        {invite_url}
      </div>
      <div style="background-color: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 20px 0; border-radius: 4px;">
        <p style="margin: 0; color: #856404; font-size: 14px;"><strong>⚠️ Important:</strong> This invitation link will expire on {expires_at}. Please complete your registration before then.</p>
      </div>
      <p>If you didn't expect this invitation, you can safely ignore this email.</p>
      <p style="margin-bottom: 0;">— The Stirling PDF Team</p>
    </div>
    <div style="text-align: center; padding: 15px; font-size: 12px; color: #777; background-color: #f0f0f0;">
      &copy; 2025 Stirling PDF. All rights reserved.
    </div>
  </div>
</div>
</body></html>"#
    );
    (body.len() <= MAX_BODY_BYTES)
        .then_some(body)
        .ok_or(MailError::InputTooLarge)
}

fn password_changed_body(
    username: &str,
    temporary_password: Option<&str>,
    login_url: &str,
) -> Result<String, MailError> {
    if username.is_empty()
        || username.len() > MAX_ADDRESS_BYTES
        || temporary_password.is_some_and(|password| password.len() > MAX_SUBJECT_BYTES)
        || login_url.is_empty()
        || login_url.len() > MAX_BODY_BYTES / 4
        || login_url.chars().any(char::is_control)
    {
        return Err(MailError::InvalidText);
    }
    let username = escape_html(username);
    let login_url = escape_html(login_url);
    let password_section = temporary_password.map_or_else(String::new, |password| {
        format!(
            r#"<div style="background-color: #f8f9fa; border-left: 4px solid #007bff; padding: 15px; margin: 20px 0; border-radius: 4px;">
  <p style="margin: 0;"><strong>Temporary Password:</strong> {}</p>
</div>"#,
            escape_html(password)
        )
    });
    let body = format!(
        r#"<html><body style="margin: 0; padding: 0;">
<div style="font-family: Arial, sans-serif; background-color: #f8f9fa; padding: 20px;">
  <div style="max-width: 600px; margin: auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; border: 1px solid #e0e0e0;">
    <div style="text-align: center; padding: 20px; background-color: #222;">
      <img src="https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/docs/stirling-transparent.svg" alt="Stirling PDF" style="max-height: 60px;">
    </div>
    <div style="padding: 30px; color: #333;">
      <h2 style="color: #222; margin-top: 0;">Your password was changed</h2>
      <p>Hello {username},</p>
      <p>An administrator has updated the password for your Stirling PDF account.</p>
      {password_section}
      <p>If you did not expect this change, please contact your administrator immediately.</p>
      <div style="text-align: center; margin: 30px 0;">
        <a href="{login_url}" style="display: inline-block; background-color: #007bff; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 5px; font-weight: bold;">Go to Stirling PDF</a>
      </div>
      <p style="font-size: 14px; color: #666;">Or copy and paste this link in your browser:</p>
      <div style="background-color: #f8f9fa; padding: 12px; margin: 15px 0; border-radius: 4px; word-break: break-all; font-size: 13px; color: #555;">
        {login_url}
      </div>
    </div>
    <div style="text-align: center; padding: 15px; font-size: 12px; color: #777; background-color: #f0f0f0;">
      &copy; 2025 Stirling PDF. All rights reserved.
    </div>
  </div>
</div>
</body></html>"#
    );
    (body.len() <= MAX_BODY_BYTES)
        .then_some(body)
        .ok_or(MailError::InputTooLarge)
}

fn user_invite_body(
    username: &str,
    temporary_password: &str,
    login_url: &str,
) -> Result<String, MailError> {
    if username.is_empty()
        || username.len() > MAX_ADDRESS_BYTES
        || temporary_password.is_empty()
        || temporary_password.len() > MAX_SUBJECT_BYTES
        || login_url.is_empty()
        || login_url.len() > MAX_BODY_BYTES / 4
        || username.chars().any(char::is_control)
        || temporary_password.chars().any(char::is_control)
        || login_url.chars().any(char::is_control)
    {
        return Err(MailError::InvalidText);
    }
    let username = escape_html(username);
    let temporary_password = escape_html(temporary_password);
    let login_url = escape_html(login_url);
    let body = format!(
        r#"<html><body style="margin: 0; padding: 0;">
<div style="font-family: Arial, sans-serif; background-color: #f8f9fa; padding: 20px;">
  <div style="max-width: 600px; margin: auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; border: 1px solid #e0e0e0;">
    <div style="text-align: center; padding: 20px; background-color: #222;">
      <img src="https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/docs/stirling-transparent.svg" alt="Stirling PDF" style="max-height: 60px;">
    </div>
    <div style="padding: 30px; color: #333;">
      <h2 style="color: #222; margin-top: 0;">Welcome to Stirling PDF!</h2>
      <p>Hi there,</p>
      <p>You have been invited to join the workspace. Below are your login credentials:</p>
      <div style="background-color: #f8f9fa; border-left: 4px solid #007bff; padding: 15px; margin: 20px 0; border-radius: 4px;">
        <p style="margin: 0 0 10px 0;"><strong>Username:</strong> {username}</p>
        <p style="margin: 0;"><strong>Temporary Password:</strong> {temporary_password}</p>
      </div>
      <div style="background-color: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 20px 0; border-radius: 4px;">
        <p style="margin: 0; color: #856404;"><strong>⚠️ Important:</strong> You will be required to change your password upon first login for security reasons.</p>
      </div>
      <div style="text-align: center; margin: 30px 0;">
        <a href="{login_url}" style="display: inline-block; background-color: #007bff; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 5px; font-weight: bold;">Log In to Stirling PDF</a>
      </div>
      <p style="font-size: 14px; color: #666;">Or copy and paste this link in your browser:</p>
      <div style="background-color: #f8f9fa; padding: 12px; margin: 15px 0; border-radius: 4px; word-break: break-all; font-size: 13px; color: #555;">
        {login_url}
      </div>
      <p>Please keep these credentials secure and do not share them with anyone.</p>
      <p style="margin-bottom: 0;">— The Stirling PDF Team</p>
    </div>
    <div style="text-align: center; padding: 15px; font-size: 12px; color: #777; background-color: #f0f0f0;">
      &copy; 2025 Stirling PDF. All rights reserved.
    </div>
  </div>
</div>
</body></html>"#
    );
    (body.len() <= MAX_BODY_BYTES)
        .then_some(body)
        .ok_or(MailError::InputTooLarge)
}

fn escape_html(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&#39;"),
            _ => escaped.push(character),
        }
    }
    escaped
}

async fn read_text(
    field: axum::extract::multipart::Field<'_>,
    name: &str,
    limit: usize,
) -> Result<String, MailError> {
    let bytes = field.bytes().await.map_err(|_| MailError::InvalidText)?;
    if bytes.len() > limit {
        return Err(MailError::InputTooLarge);
    }
    let value = String::from_utf8(bytes.to_vec()).map_err(|_| MailError::InvalidText)?;
    SecurityAuditContext::record_current_form_param(name, &value);
    Ok(value)
}

fn safe_attachment_filename(filename: Option<&str>) -> Result<String, MailError> {
    let filename = filename
        .and_then(|value| value.rsplit(['/', '\\']).next())
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .ok_or(MailError::MissingAttachment)?;
    if filename.len() > MAX_FILENAME_BYTES || filename.chars().any(char::is_control) {
        return Err(MailError::InvalidText);
    }
    Ok(filename.to_owned())
}

fn parse_mailbox(value: &str) -> Result<Mailbox, MailError> {
    let value = value.trim();
    if value.is_empty() || value.len() > MAX_ADDRESS_BYTES {
        return Err(MailError::InvalidAddress);
    }
    value.parse().map_err(|_| MailError::InvalidAddress)
}

pub(crate) fn is_valid_recipient(value: &str) -> bool {
    parse_mailbox(value).is_ok()
}

fn mail_error_response(error: &MailError) -> Response {
    text_response(
        StatusCode::INTERNAL_SERVER_ERROR,
        &format!("Failed to send email: {error}"),
    )
}

fn tls_parameters(host: &str) -> Result<TlsParameters, MailError> {
    TlsParameters::new(host.to_owned()).map_err(|_| MailError::InvalidConfiguration)
}

fn text_response(status: StatusCode, text: &str) -> Response {
    (
        status,
        [(header::CONTENT_TYPE, "text/plain; charset=utf-8")],
        text.to_owned(),
    )
        .into_response()
}

#[cfg(test)]
mod tests {
    use super::{
        MailError, invite_link_body, password_changed_body, safe_attachment_filename,
        user_invite_body,
    };

    #[test]
    fn attachment_names_are_reduced_to_safe_basenames() -> Result<(), MailError> {
        assert_eq!(
            safe_attachment_filename(Some("../exports/report.pdf"))?,
            "report.pdf"
        );
        assert!(safe_attachment_filename(Some("bad\r\nname.pdf")).is_err());
        assert!(safe_attachment_filename(None).is_err());
        Ok(())
    }

    #[test]
    fn invitation_template_escapes_dynamic_html() -> Result<(), MailError> {
        let body = invite_link_body(
            "https://pdf.example.test/invite/token?next=<admin>&team=R&D",
            "2030-01-01T00:00:00+00:00",
        )?;
        assert!(!body.contains("next=<admin>"));
        assert!(body.contains("next=&lt;admin&gt;&amp;team=R&amp;D"));
        Ok(())
    }

    #[test]
    fn password_template_escapes_values_and_controls_password_visibility() -> Result<(), MailError>
    {
        let hidden = password_changed_body(
            "user<&>@example.test",
            None,
            "https://pdf.example.test/login?next=<admin>&team=R&D",
        )?;
        assert!(hidden.contains("Hello user&lt;&amp;&gt;@example.test"));
        assert!(!hidden.contains("Temporary Password:"));
        assert!(hidden.contains("next=&lt;admin&gt;&amp;team=R&amp;D"));

        let included = password_changed_body(
            "user@example.test",
            Some("unsafe<&>password"),
            "https://pdf.example.test/login",
        )?;
        assert!(included.contains("Temporary Password:</strong> unsafe&lt;&amp;&gt;password"));
        assert!(!included.contains("unsafe<&>password"));
        Ok(())
    }

    #[test]
    fn account_invitation_template_escapes_credentials_and_login_url() -> Result<(), MailError> {
        let body = user_invite_body(
            "user<&>@example.test",
            "unsafe<&>password",
            "https://pdf.example.test/login?next=<admin>&team=R&D",
        )?;
        assert!(body.contains("Username:</strong> user&lt;&amp;&gt;@example.test"));
        assert!(body.contains("Temporary Password:</strong> unsafe&lt;&amp;&gt;password"));
        assert!(body.contains("next=&lt;admin&gt;&amp;team=R&amp;D"));
        assert!(!body.contains("unsafe<&>password"));
        Ok(())
    }
}
